### ISSUE TITLE
RFC: move all scripts to composer scripts

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#1019]
Currently there are multiple places where scripts for running tests etc are defined.

* ```Makefile```
* ```script/```
* ```.travis.yml```

I'd propose to define them in composer scripts, so we can run ```composer test``` or ```composer cs``` etc. 
We could then delete the ```Makefile```,  `script/`, and update `.travis.yml` to use the composer scripts. And of course update documentation. 

This has the following advantages
* Less files to maintain
* Allows windows users to use the commands (`make` isn't really a windows thing)
* Gives a bit more security that if tests pass on your system it will also pass on travis.

**Comment by localheinz** [comment]
I don't care much whether we use `Makefile` or `composer `scripts as long as I have short and simple commands available to build locally.

In regard to some duplication between `.travis.yml` and `Makefile`: I can think of a single reason why that is fine, and that is that it is easier to see which step failed when there are  multiple steps defined (rather than `composer make` or `make`), and therefore I think it's worth paying the price of duplication.

I'm totally 👍 for replacing `/scripts` with either targets in `Makefile`, or `composer` scripts.

Maybe it's a good idea to do this in multiple steps?

For a start, we could move everything in `/scripts` into the `Makefile`, and then revisit.

For reference, also see http://fabien.potencier.org/symfony4-best-practices.html.

**Comment by mdwheele** [comment]
I'm 100% on consolidating to one and making Travis do *exactly* what we do to set up.

That said, the current `Makefile` makes a assumptions about the environment and cannot be used for anything other than a local development setup. I run OpenCFP in a Docker environment that separates Selenium, MariaDB, Nginx and PHP-FPM into different containers. Current setup process assumes database is available via `localhost`, etc. Leads to me just doing my own thing; extra work. 

I would prefer something that is able to be parametrized (possibly via environment variables) which could be done no matter the direction; just voicing the concern. I am not suggesting that is within scope here, but is worth considering when picking a solution (i.e. it needs to be configurable without editing targets by hand).

For information, the `/scripts` concept was originally introduced based on standards GitHub adopted in their projects (https://github.com/github/scripts-to-rule-them-all). There *is* an argument to be made in having explicated ubiquitous targets for doing executing common application procedures. Pretty sure that can be done in a `Makefile` as well.

> I'd propose to define them in composer scripts, so we can run composer test or composer cs etc.

This is not an argument against, just food for thought: Composer imposes a 300 second `max_execution_time` that is configurable via environment variable. Not too big of a deal, but worth consideration.

> Allows windows users to use the commands (make isn't really a windows thing)

Having run PHP binaries on Windows; it's a thing. It works. Hosting a PHP application in Apache (on Windows) is troublesome and hosting PHP in IIS is... "fun". My recommendation to a lot of Windows folks is to buy into Docker and Windows 10 ASAP and if that isn't an option, Vagrant + VirtualBox (or something like Laravel Homestead). It is rare for me to run into someone still on WAMP / XAMPP. I think the community has made getting into virtualization easier than it used to be.

> Gives a bit more security that if tests pass on your system it will also pass on travis.

🎉 This is 9001% the reason to do this, in my opinion.

> Maybe it's a good idea to do this in multiple steps?

Please don't open PRs per-file / line change! I think larger-than-per-line logical units of work could be merged and there'd be less limbo-time to move forward. I think first step is figuring out which we're going to use. Then I would like to reconsider current targets. Part of that will be considering Symfony "best practice" targets as well as current scripts-to-rule-them-all.
