### ISSUE TITLE
Replace home-made and Illuminate validation with Symfony validation

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#1023]
Currently we are using a bit of 

* home-made validation
* validation using Illuminate
* no validation

Ideally, we should be consistently using one kind of validation, and especially since we have turned this into a Symfony application, I suggest we use [`symfony/validator`](https://github.com/symfony/validator).

Related to #1020.

**Comment by BackEndTea** [comment]
> validation using Illuminate

This one is only used in the base controller, so once we extract all controllers into actions this *should* be resolved.

On that note, the only place we use `illuminate/validaton`, `illuminate/container` or `illuminate/events` is in the base controller in the validation function. So once refactor that out we can drop those 3 dependencies.

**Comment by mdwheele** [comment]
Oh, and there is 100% an argument for "We're using Symfony, we should use Symfony". 

😁
