### ISSUE TITLE
Better handling and testing of emails

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#1032]
In reality this is really two requests

## Async handling of emails
The sending of emails should be handled a-sync, and should have no impact on the submitting of talks. Currently on master, if the email has an issue we get an error displayed.

## Testing of sending emails
Although it is good practice to make sure we don't send emails during tests, it does mean that our tests don't cover the sending of emails.

Maybe we can use [mailcatcher](https://github.com/sj26/mailcatcher) in some form to check if everything works correctly when we send emails, and that those get sent properly, assuming config was done correctly.
Ideally there should be two tests for this. One with everything set up correctly, making sure that the mail ends up in mailcatcher, another test with a faulty mail set up, confirming that the end user doesn't see all kinds of errors. 

Somewhat related to https://github.com/opencfp/opencfp/pull/1021#issuecomment-353548051

**Comment by chartjes** [comment]
Restmail is also very good for this -- I use it at Mozilla to test a system where changes to records stored in a database correctly trigger emails.

I uses a nice API that we can hit directly with guzzle (or your HTTP client of choice)
