### ISSUE TITLE
Margins are broken

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#1033]
# Steps required to reproduce the problem

1. Create project from current `master`
2. Take a look at pages

# Expected Result

* looking good

# Actual Result

![screen shot 2017-12-22 at 09 36 13](https://user-images.githubusercontent.com/605483/34291256-b2536028-e6fb-11e7-9844-bbf00254b015.png)
![screen shot 2017-12-22 at 09 36 16](https://user-images.githubusercontent.com/605483/34291257-b26f9194-e6fb-11e7-83e5-7a8fed176d29.png)
![screen shot 2017-12-22 at 09 36 19](https://user-images.githubusercontent.com/605483/34291258-b288c51a-e6fb-11e7-942c-a4b4089b9ea2.png)
![screen shot 2017-12-22 at 09 38 37](https://user-images.githubusercontent.com/605483/34291304-f3ef2d0a-e6fb-11e7-91cc-72d78ab128a1.png)
![screen shot 2017-12-22 at 09 38 43](https://user-images.githubusercontent.com/605483/34291305-f4081f04-e6fb-11e7-917a-10d4bbeb5cf9.png)

Probably related to #990.

**Comment by BackEndTea** [comment]
#1016 should fix this

**Comment by localheinz** [comment]
@BackEndTea 

Would you like to approve and merge #1016?
