### ISSUE TITLE
CFP closed view

### ISSUE THREAD

**Issue by pmeth** [opencfp/opencfp#107]
Once the CFP end date has passed, there is no visual indicaton on the homepage.  The only indication I see is when someone tries to login or create an account.

Also I think we should still probably let people create accounts and login after the CFP is closed, but just not let them submit talks.  For example, how is an administrator supposed to login to perform administrative tasks?

**Comment by mdwheele** [comment]
@pmeth This is pretty old at this point. I've got a few updates and some next steps:

- [ ] There should be visual indication on homepage once the CFP is closed.
  - What should that look like? e.g. "Sorry folks, [...]. Try again next year!"?
- [x] Speakers and admins are able to authenticate after the CFP is closed.
- [x] Speakers cannot submit, edit, or remove talks after CFP is closed.
- [x] Should be able to promote existing users to admin after CFP ends.
- [ ] Should be able to create admin users when they don't already exist with CLI utility.
  - `bin/opencfp admin:promote email` could create the account, emailing user to continue the activation / specifying-password flow. Shouldn't be that difficult and would actually be a good spring-board for wrapping authentication.

If visual indication of closure were implemented in addition to a separate issue detailing "admin user creation" being created, do you think we could close this out as resolved?

**Comment by mdwheele** [comment]
@pmeth Are we good to close this issue out? I'm going to create an issue for the incomplete bullet point above, but since it's not entirely related to this issue, I think everything else is accomplished?
