### ISSUE TITLE
RFC: Use correct request types

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#1070]
Some actions, like the speaker promote action sould be post requests, since they alter something, but instead they are GET requests.

These have to be updated to be POST requests, and maybe some logic has to change as well if that changes behaviour.

Somewhat related to: #1068

The routes that have to be updated are:

* [ ] `admin_speaker_promote`
* [ ] `admin_speaker_demote`
*  [ ] `admin_speaker_delete`
* [ ] `reset_password`

And per route the following things have to be changed
* `routing.yml`
* Convert the response to a `JsonResponse` and use that
* Change front-end logic to handle the new behavior
* Integration tests relating to the route
* Unit tests relating to the route

**Comment by chartjes** [comment]
👍 to this
