### ISSUE TITLE
Ask only for the username for Joind.in-Link 

### ISSUE THREAD

**Issue by heiglandreas** [opencfp/opencfp#1083]
# Feature-Request:

Currently users can add a link to their joind.in profile. For that they need to enter the complete URL.

In my opinion it would be easier to let users enter their joind.in-username and to create the link  for them. That would then be the same process as for twitter.

**Comment by localheinz** [comment]
Sounds good to me, @heiglandreas!

**Comment by derrabus** [comment]
Migrating this could be ugly if users have already used that field for URLs other than a joind.in profile link.

**Comment by chrisforrence** [comment]
@derrabus Fortunately (?), it looks like the validation for the URL had been restricted to joind.in links anyways, so users wouldn't have been able to put in other URLs
