### ISSUE TITLE
Password reset does not work, results in Internal Server Error

### ISSUE THREAD

**Issue by stevecoug** [opencfp/opencfp#1089]
# Steps required to reproduce the problem

1. Click on "Forgot Password"
2. Enter email address and submit
3. Click on link received via email
4. Enter new password (twice) and submit

# Expected Result

* Password changed successfully

# Actual Result

* Internal Server Error
`[2018-01-25 15:57:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to OpenCFP\Infrastructure\Auth\SentinelAccountManagement::findById() must be of the type integer, string given, called in /var/www/cfp.openwest.org/classes/Http/Action/Forgot/UpdatePasswordAction.php on line 86" at /var/www/cfp.openwest.org/classes/Infrastructure/Auth/SentinelAccountManagement.php line 33 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to OpenCFP\\Infrastructure\\Auth\\SentinelAccountManagement::findById() must be of the type integer, string given, called in /var/www/cfp.openwest.org/classes/Http/Action/Forgot/UpdatePasswordAction.php on line 86 at /var/www/cfp.openwest.org/classes/Infrastructure/Auth/SentinelAccountManagement.php:33)"} []`

**Comment by chartjes** [comment]
@stevecoug What release of OpenCFP are you currently using?

**Comment by stevecoug** [comment]
We're bleeding edge...
I'm working on a fix. I've got a temporary fix (call intval on the user_id), but I'm looking into how it gets called, and getting some tests around it.

**Comment by chartjes** [comment]
I have also been debugging the issue and I can't even get it to email anything...looks like the swiftmailer object isn't being configured correctly

**Comment by stevecoug** [comment]
I received the emails just fine, so it may just be your environment.

**Comment by chartjes** [comment]
Yeah, once I did script/setup things are fine.

I did figure out the problem -- in `UpdatePasswordAction` we need to explicitly cast the user_id to be an integer when we pull it out of the data from the form. 

I will patch that up, fix any tests, and then close this issue.

Thanks so much for pointing that out to us

**Comment by stevecoug** [comment]
That's what I did on my end, but I was going to see if it could be corrected elsewhere. I hate just casting stuff to an int as a fix. 😃

**Comment by chartjes** [comment]
Probably the best way to do it anyway

**Comment by stevecoug** [comment]
Could make the Sentinel have some logic to determine if it's a numeric string, but that doesn't seem right. Is the form defined somewhere, where we could force it to expect user_id to be an integer?

**Comment by chartjes** [comment]
Our implementation always assumes it is an integer, but I will look and see if the form can force the return of that value as an integer.

**Comment by llbbl** [comment]
Can we get a new tag release to cover this fix? 1.5.1?
