### ISSUE TITLE
[1.5.1+] Need a unique file to OpenCFP for Laravel Valet Custom Driver

### ISSUE THREAD

**Issue by llbbl** [opencfp/opencfp#1101]
Since the 1.5 refactor got rid of this file: 
> /bin/opencfp 

We no longer have a good file to check against the existence of for the Laravel Valet Custom Driver. I have updated it to use a migration temporarily but I would like something nicer and more permanent.  

I would like to submit a PR for a hidden file or something like
- .opencfp.keep

I don't care what its called, but it needs to be something unique to opencfp so might as well have project name in the file name. 

I added instructions wiki last night only to discover today that this no longer works for 1.5. 
https://github.com/opencfp/opencfp/wiki/Laravel-Valet-Custom-Driver

**Comment by chartjes** [comment]
@libbl I would happily accept a PR to add a file like this for Laravel Valet

**Comment by llbbl** [comment]
Thanks for the quick reply. PR inc.

**Comment by mdwheele** [comment]
@llbbl 

Would you be amenable to (assuming this works for Valet):

```php
public function serves($sitePath, $siteName, $uri)
{
    $composer = json_decode(file_get_contents($sitePath . '/composer.json'), true);

    return $composer['name'] == 'opencfp/opencfp';
}
```

This way, there is no need for a marker file other than `composer.json` to specify something OpenCFP-specific.

**Comment by llbbl** [comment]
@mdwheele I guess that works yea. Let me check the performance impact.

**Comment by llbbl** [comment]
@mdwheele yea its fine. (or at least something similar) i'll close the PR and update the wiki. 

I think that method has to return true or false, so I just modified what you posted so it does that.
