### ISSUE TITLE
[FEATURE REQUEST] Add a way to export selected talks to joind.in

### ISSUE THREAD

**Issue by heiglandreas** [opencfp/opencfp#1108]
As an Event-Organiser I would like to be able to add selected talks to my event on joind.in

**Comment by chartjes** [comment]
To clarify your request:

An Admin should have the ability to select certain talks and then create a download with talks + speaker information that can be imported into joind.in?

**Comment by heiglandreas** [comment]
Actually more like "An admin can register the OpenCfP-Instance as third-party app in [joind.in](https://joind.in/user/[userid]/client/), add the received token to OpenCFP and is then able to push talks via the joind.in API to joind.in"

I'd see this as a plugin if there is a plugin-system available for OpenCFP… ;)

**Comment by chartjes** [comment]
@heiglandreas I am finally starting to spec out OpenCFP Central and I could definitely see this as a feature being made available there.

**Comment by heiglandreas** [comment]
Though that feature might need some work on the joind.in-Side to allow "talk-templates" in joind.in that might miss some of the required fields. Depending on how "finished" the talks are added to joind.in. It would also allow updates to the joind.in-talks via the API so the event-organizer would only need ONE place to maintain the talks…
