### ISSUE TITLE
"bin/console server:start" (in production env) throws "There are no commands defined in the "server" namespace."

### ISSUE THREAD

**Issue by andygrunwald** [opencfp/opencfp#1120]
# Steps required to reproduce the problem

1. `git clone https://github.com/opencfp/opencfp.git`
2. `cd opencfp && script/setup`
3. `cp config/production.yml.dist  config/production.yml`
4. `export CFP_ENV=production`
5.  `bin/console server:start`

# Expected Result

* A running opencfp with the PHP internal web server as described here in the README: https://github.com/opencfp/opencfp#php-built-in-web-server

# Actual Result

Error message
```
  There are no commands defined in the "server" namespace.
```

# Possible solution

After applying
```
export CFP_ENV=development
cp config/development.yml.dist config/development.yml
bin/console server:start
```

it works as expected.
Maybe a small note into the README that this only works in development mode might be useful for starters/beginners with OpenCFP.

On the Symfony docs [How to Use PHP's built-in Web Server](https://symfony.com/doc/current/setup/built_in_web_server.html) there is a warning like

> The built-in web server is meant to be run in a controlled environment. It is not designed to be used on public networks.

which make sense. I agree. But I found this warning only after clicking the link and it was not obvious to me at first.
So I would not consider this issue as a bug. More as a small improvement to make this app more accessible to less experienced users with PHP (who are not able to figure this out).

PS: Thanks for this application :)

**Comment by chartjes** [comment]
@andygrunwald Would be happy to accept a PR to the documentation with this update in it

**Comment by andygrunwald** [comment]
I will prepare one on the next days.

Chris Hartjes <notifications@github.com> schrieb am Fr. 30. März 2018 um
21:35:

**Comment by andygrunwald** [comment]
See https://github.com/opencfp/opencfp/pull/1122
