### ISSUE TITLE
Avoid external network calls to services like Github, Jquery, Google Fonts and so on

### ISSUE THREAD

**Issue by andygrunwald** [opencfp/opencfp#1121]
# Steps required to reproduce the problem

1. Install OpenCFP in development mode (e.g. via internal PHP web server)
2. Open http://127.0.0.1:8000/ in a browser and check out your network/developer console

# Expected Result

All sources that are required to load the start page are requested locally from 127.0.0.1

# Actual Result

Several network calls are using external resources which require an active internet connection.
Examples from the start page:

* jquery via https://code.jquery.com/jquery-3.2.1.min.js
* "Fork me on github" logo via https://camo.githubusercontent.com/a6677b08c955af8400f44c6298f40e7d19cc5b2d/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67
* Google font "Roboto|Zilla Slab" via http://fonts.googleapis.com/css?family=Roboto|Zilla+Slab AND https://fonts.googleapis.com/css?family=Roboto|Zilla+Slab
* `woff2` file for Google font "Roboto|Zilla Slab" via https://fonts.gstatic.com/s/zillaslab/v3/dFa6ZfeM_74wlPZtksIFajo6_V6LVlA.woff2

# Context

To load these resources locally would have many advantages:

* it would be possible to develop OpenCFP in envs where no (stable) internet connection is available (eg in a train)
* the start page would load faster because the resources are used locally instead of externally
* maybe better/more data protection, the external resources know where the request comes from (just a guess, i am not a security expert)

**Comment by chartjes** [comment]
@andygrunwald You do raise a good point about this.

@mdwheele Is this a reasonable change?
