### ISSUE TITLE
`server:start` Command does not work (It has no constructor arguments)

### ISSUE THREAD

**Issue by kolibri** [opencfp/opencfp#1128]
# Steps required to reproduce the problem

```bash
> git clone git@github.com:opencfp/opencfp.git
> cd opencfp
> ./script/setup
> cp config/development.yml.dist config/development.yml
> ./bin/console server:start
# or
> ./bin/console server:start --docroot=web --env=development
```

# Expected Result

A running dev server ;)

# Actual Result

```bash
> ./bin/console server:start

[ERROR] The document root directory must be either passed as first argument of the constructor or through the "docroot" input option.

# or 

> ./bin/console server:start --docroot=web --env=development

 [ERROR] The environment must be passed as second argument of the constructor.
```

I checked the constructor of the `\Symfony\Bundle\WebServerBundle\Command\ServerStartCommand` and it is true, it is called without arguments. But every other code (service definitions, compiled container, `./bin/console debug:container --parameters`) shows the parameters, and that they are given to the Command.
I have no clue, where are these arguments are lost.

Did I miss something?

**Comment by chartjes** [comment]
@kolibri That is definitely broken. Don't know what happened :(

I'll see about fixing this as soon as I can

**Comment by zymsys** [comment]
Composer update fixes this for me. I have a feeling it is to do with using symfony/console 4.0 with Symfony 3.4, and to do with the removal of command auto-registration. This was causing the server start command constructor to be called with default arguments. I'm not sure what in the update actually resolved the problem, but it did work for me.
