### ISSUE TITLE
Create User Export Functionality

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#1135]
In order to be GDPR compliant, we need to add functionality to allow a specific speaker, upon request, to be able to download an archive with all the data they have entered into the system

**Comment by josegonzalez** [comment]
I assume this will mean building a tarball of their talks, profile, and any uploaded image assets? Having only used opencfp as a speaker submitter, not sure what other knobs there would be.

**Comment by chartjes** [comment]
Also need to grab any ratings of talks that a user made
