### ISSUE TITLE
Allow all data associated with a speaker account to be deleted

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#1137]
In order for this application to be GDPR compliant, we need to provide functionality to delete all data associated with a speaker:

* speaker account
* all talks associated with that speaker

**Comment by Jean85** [comment]
Maybe it's good to also create a GDPR milestone here? So it would be easier to track progress between issues and PRs...

**Comment by yitznewton** [comment]
Any preference as to how to present the control? Something like:

![image](https://user-images.githubusercontent.com/619299/39582958-0dc91c12-4ebd-11e8-80a4-5c29b98195d4.png)

**Comment by mdwheele** [comment]
> Any preference as to how/where to present the control?

Could it be placed as a secondary action alongside their other actions the user can perform at the top? Perhaps with a client-side confirmation as well.

> In terms of work flow, should destroying the account data also log them out of the system upon resolution?

I think their current active session should be included in "their data" and be cleaned up. From a strictly technical perspective, if the account is destroyed, the session they would retain would be for a Null User, which would be awkward.
