### ISSUE TITLE
Support heroku-based installation

### ISSUE THREAD

**Issue by josegonzalez** [opencfp/opencfp#1138]
In typical cowboy coding, I am loathe to setup foreign applications locally, and generally push changes to some ~~production~~ _staging_ server, relying on CI to verify that I didn't break stuff - and that new functionality works as desired.

Would you be open to supporting heroku-based installation in mainline? There are a few minor changes to be made - mostly adding files and updating the composer.json - but I don't want to contribute them if you're not open to doing so.

**Comment by chartjes** [comment]
Yes, making this app deployable to Heroku is a long-term plan and I would happily merge in PR's that make that an option.
