### ISSUE TITLE
Implement data retention policy

### ISSUE THREAD

**Issue by Synchro** [opencfp/opencfp#1139]
GDPR requires that you have a defined data retention policy, after which personal data is deleted automatically. For OpenCFP it might be reasonable to default to something like 15 months to allow for year-to-year continuity for annual conferences.

**Comment by chartjes** [comment]
@Synchro I'm not sure how effective that will be because I do not have a way to force existing OpenCFP instances to purge their data. It is up to the folks running that instance to comply with the law, all I can do is provide tools to enable them to be compliant.

If I was running OpenCFP as some kind of centralized platform, yes, I would need that policy and would be required to purge data in accordance with GDPR

**Comment by chartjes** [comment]
I am unsure how to "force" the deletion of data. Do I have to start having the app "phone home" and then delete data remotely? I'm not being sarcastic, I am wondering how to do this part.

**Comment by Synchro** [comment]
Phone home to where? Have I misunderstood how OpenCFP gets deployed? All I'm suggesting is like #1137, but driven from some cron job according to the retention policy instead of manual request. I presume you track when a user last interacted with the app (if not, you'd need that), so it should be as simple as "delete any user that has not logged in for *x* months".

I know quite a few apps do a kind of random chance of running a housekeeping task on any request (by anyone) as a kind of poor-man's cron.

**Comment by chartjes** [comment]
People deploy OpenCFP themselves -- I cannot make any assumptions about their ability to run cron jobs. I have no idea what OS or shell they have picked.

This is not to say I don't like the idea -- we can certainly add code in to allow people to run it as a cron job but I have no way to force them to run it.

We don't track the last time a user logged in anywhere in the application as that is not required for any functionality in the app itself.

**Comment by luceos** [comment]
Offering a way to adhere to the guidelines increases the chance that solution is utilised tremendously. Not offering any solution is a guaranteed problem as all people with good intentions using openCFP will need to come up with their own implementations 🤷‍♂️

**Comment by chartjes** [comment]
@luceos I definitely want to add support for it!

**Comment by Synchro** [comment]
Indeed - that's the whole point of privacy by design: if you do nothing, data should be managed appropriately, privacy preserved. The last login date is obviously a trivial addition, the retention policy and automated application of it is slightly more involved, but at least there's now an issue to act as a target for a PR...

**Comment by ElectricMaxxx** [comment]
I made a duplicate right: #1133 ?
