### ISSUE TITLE
Joind.in regex doesn't allow full stop in username

### ISSUE THREAD

**Issue by dzoeteman** [opencfp/opencfp#1161]
# Steps required to reproduce the problem

1. Have full stop in joind.in username
2. Try to enter joind.in URL on profile page

# Expected Result

*  No error

# Actual Result

* Error will be displayed "You did not enter a valid joind.in URL"

**Comment by chartjes** [comment]
@dzoeteman Could you explain for me what a full stop is? Sorry, not familiar with that term

**Comment by dzoeteman** [comment]
@chartjes A period, as in `firstname.lastname`.
