### ISSUE TITLE
RFC: Web-based admin panel

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#1173]
Wondering how much value there might be in adding an admin module that can be used to set a lot of the values in our various configuration files, especially if we start making it easier for the application to be deployed to PaaS solutions like Heroku or Platform.sh.

**Comment by iansltx** [comment]
Would this result in config being moved out of yaml and into something that would be more readily writable in a default read only context (e.g. Platform.sh), or would changes assume that the yaml file is writable and go from there? To be fair, I might be mis-characterizing Platform.sh's rules.

**Comment by chartjes** [comment]
I am thinking of having a very minimal yaml configuration and then moving everything else into the database along with an admin panel to set them. Most PaaS offerings seem to limit your ability to write things to a filesystem so storing them in a DB seems to make sense to me.

**Comment by iansltx** [comment]
Makes sense to me. Seems like slimming down the yaml config to just contain secrets would work out well.

One catch is that stuff in the DB doesn't give you version control for free like a yaml file would, but if your talk config is in the same file as your database creds then that entire file isn't in a VCS anyway (at least, it isn't for our current deploy).
