### ISSUE TITLE
Enhancement: push admins to admin dashboard right after login

### ISSUE THREAD

**Issue by iansltx** [opencfp/opencfp#1183]
My thought here (from experience) is that admins aren't going to be submitting abstracts to their own conferences, so when they log in, the admin dashboard is a *much* more useful place to land.

I'm not sure of the effort required to make this tweak, but if the above sounds like something merge-able if I get a working PR for it, I'll definitely have a go at it, as I'll definitely benefit from the feature.

**Comment by chartjes** [comment]
I like that idea

**Comment by iansltx** [comment]
Dangit, forgot to link the PR to the issue. https://github.com/opencfp/opencfp/pull/1187

Tests are failing for some reason right now so I'll get those fixed and then tag you for review there.
