### ISSUE TITLE
Enhancement: On dashboard, show count of speakers who have submitted >= 1 talk

### ISSUE THREAD

**Issue by iansltx** [opencfp/opencfp#1197]
Right now the "speakers" count on the admin and reviewer dashboards includes all users, including admins and other folks who haven't submitted a talk (or won't).

Just revised that on our fork to show only speakers who have submitted at least one talk, and renamed the UI element to "Speakers w/Talks", as that's a bit more useful metric, at least for us. Wouldn't be too terribly difficult to make which number gets shown configurable, though of course it's easier to just switch what number gets displayed wholesale.

If there's interest in this, I'll work on a PR. For those interest, let me know if y'all want the configurable version (in which case I'd default it to the current behavior) or the non-configurable version.

**Comment by chartjes** [comment]
I would be interested in a version that lists number of "speakers with talks" in that admin and reviewer dashboards because that reflects what is important.

Configurable is nice but I would suspect most folks would just leave it at the default value
