### ISSUE TITLE
See Votes of reviewer

### ISSUE THREAD

**Issue by martinthalmann** [opencfp/opencfp#1212]
# Steps required to reproduce the problem
We use opencfp for the DevOpsDays Zurich (Thanks a lot - it helps a lot and simplifies the process). We already have many talks that have been rated by our reviewers. Now we would like to put together the final program in the core team (we all have the admin rights). It would be extremely important to see how many reviewers like or don't like a certain talk. I couldn't find this function neither in the GUI nor in the CSV file.

Is there a way to get this information? Or would we have to read it from the database?

# Expected Result

* 

# Actual Result

*

**Comment by chartjes** [comment]
Hi @martinthalmann.

You would have to read that information from the database at this time.

**Comment by martinthalmann** [comment]
thanks for the quick response @chartjes .... will check that directly in the database :)
