### ISSUE TITLE
Do not output email exceptions directly to output

### ISSUE THREAD

**Issue by lisachenko** [opencfp/opencfp#1213]
# Steps required to reproduce the problem

1. Have broken Swift connection
2. Submit a talk
3. Receive plain output with a Swift exception trace

# Expected Result

* Polite information about technical issues on the site and reported exception in server log

# Actual Result

* Raw exception output

**Comment by chartjes** [comment]
Hi @lisachenko, thanks for submitting the bug report. I've assigned it to myself to fix.
