### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by exussum12** [opencfp/opencfp#1214]
More of a question than an issue.

Currently the docker container is broke because it follows "latest" (fix unmerged here https://github.com/linuxjuggler/php-and-nginx/pull/2)

Is there a reason this is used and not the combination of 2 official images ?

**Comment by chartjes** [comment]
No real reason, would happily accept a PR that fixes this issue.

**Comment by leafnode** [comment]
PR #1216 submitted.
