### ISSUE TITLE
Reviewer can freely list all other reviewers

### ISSUE THREAD

**Issue by DarGrze** [opencfp/opencfp#1215]
# Steps required to reproduce the problem

1. Promote user to reviewer
2. login as reviewer
3. list users.

# Expected Result

* A possibility to decide whether the reviewer list can be spreaded among all other reviewers or not (perhaps in config).

# Actual Result

* It can be problematic (see for ex. GDPR), especially if you want to grant reviewer rights to wider group of people.
* For now, it excludes quite fancy possibility of a semi-public voting for proposals - after promoting all attendees to the reviewer role.

**Comment by chartjes** [comment]
I fixed this in the master branch as part of a previous commit.

**Comment by DarGrze** [comment]
So, sorry so much for my noise. I didn't find it.

Thanks a lot!
-- Darek.

wt., 5 mar 2019, 18:37 użytkownik Chris Hartjes <notifications@github.com>
napisał:
