### ISSUE TITLE
Remind users who have registered they have no talks submitted

### ISSUE THREAD

**Issue by jsundquist** [opencfp/opencfp#159]
As of right now there is no way to trigger users to remind them that they have registered to the call for papers site and have not submitted any talks yet.  It might be a nice enhacement to be able to send an email to those users that the call for papers closes on X date and they have not submitted, or possibly inform all users they have submited x, talks as a reminder to submit soon.

**Comment by chartjes** [comment]
Closing due to length of open issue (I want to get rid of issues that are more than a year old)
