### ISSUE TITLE
Functional tests are too specific to default config values

### ISSUE THREAD

**Issue by jakefolio** [opencfp/opencfp#161]
If I try to run the functional (behat) tests on my local install for Lone Star PHP, tests will fail. The tests fail because they're looking for specific dates that are default values. I think the behat tests should be re-evaluated to avoid testing default values from the config and text that will most likely change from each install. I think if we put the emphasis on testing flash messages to verify expected outcome that those tests will yield a greater value.

**Comment by mdwheele** [comment]
Functional tests have been removed in favor of improving controller coverage through unit tests. Behat suite was completely intended to provide rough "coverage" over most important use-cases while a large refactor happened a while ago. 

An abstraction providing information on whether or not the CFP is open is now available (`CallForPapers->isOpen()`) that is meant to be used as configuration dependency of service layer implementations. In this way, testing boundaries is easier as mocking that dependency (or simply new-ing it up with an intended date) is possible.
