### ISSUE TITLE
Transition from Sentry to Silex Security

### ISSUE THREAD

**Issue by jakefolio** [opencfp/opencfp#163]
Sentry is no longer being supported/maintained, and I think it would be best to move away from it. We need to rid ourselves of the multiple DB libraries and this move will allow that. My suggestion is to move to something like: https://github.com/jasongrimes/silex-simpleuser

I would love to hear some feedback on this topic.

**Comment by chartjes** [comment]
Okay, I'm taking this over and making all the necessary changes to support it.

**Comment by mdwheele** [comment]
Cartalyst released Sentinel as FOSS as well since we started this. It's basically Sentry, but supported. May be worth consideration if you hit friction implementing silex security.

**Comment by mdwheele** [comment]
Forgot link https://github.com/cartalyst/sentinel

**Comment by chartjes** [comment]
Closing because I feel a better upgrade path is to move to Sentinel
