### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#171]
With so much of the application bootstrap changed recently and with the introduction of request interface-specific namespace patterns and the beginnings of a service layer, I think now is a good time to draft a light-weight document that attempts to answer the question of "Where does this-or-that go?". 

I'll send along a PR that includes a `contributing.md` that details:

* Current and Intended Application Architecture  
We're currently in a transitional state of writing a service-layer using logic represented in controller methods for the purposes of building alternate request interfaces to the application.
* How to go about writing command-line utilities (and the types of things we're looking for)
* How to go about working with HTTP (api / web)  
* Thoughts on how to go about implementing new features (possible suggestions of representing features as storybdd and working outside in... I think this is too opinionated for ocfp, but I'll write it up for review and see what we get).  The important thing is to make sure people understand that as we move towards a service-layer, new features should be implemented behind that wall and exposed strategically to intended request interfaces.

**Comment by mdwheele** [comment]
Dropping some notes here. Going to get on a whiteboard sometime tomorrow or so and draw some simple diagrams up.

**Handling Requests**

Important to think of application as almost an onion with layers. The application is going to handle requests coming in and issue appropriate responses, yadda yadda.

There are a few types of requests that can come in:

* Web UI Requests (the current web application)
* JSON API Requests (pending)
* Console Requests

These are considered "Request Gateways" that translate raw data payloads into a native format to be used in a layer closer to our domain model. That sounds overcomplicated... an example would help, but I will need to make this not sound so technical... because it's not.  For example, Web UI requests are going to be making GET requests with query parameters and sending POST with form-url-encoded bodies... either way, you're probably processing this with the Symfony Request object or similar framework-specific thing-or-another. Another example is our JSON API where instead of form-url-encoded bodies, you have JSON bodies flying around.  Yet *another* example is our console request gateway where we're processing arguments and options at the CLI.

These gateways are represented by controllers in appropriate namespaces (that are currently under debate):

* Web Requests might go to `OpenCFP\Http\Web`
* JSON API Requests might go to `OpenCFP\Http\Api`
* Console might go to `OpenCFP\Console`

I don't like this particular namespace layout because I want to see all my controllers processing requests at the edge of the system in one namespace, split on gateway. Will need to revisit this.  However, it's really most important to understand that by having multiple gateways, you have potential for duplication of logic in controllers between console, web, and API.  **That** is the biggest benefit of an Application Service Layer (currently represented in the `OpenCFP\Application` namespace)

A TON of this is in flux at the moment so you'll see form stuff in the controller namespace... that's okay. Nobody is dying or anything. But a justification for that *might* be that since it could only have to do with validating web form requests, it actually is where it should be... that's not the case so much here because we're using those in places for model validation; food for thought towards the future.

So, controllers should be pretty light in the **long-term** as they move towards using a currently non-existent application service layer. Application services will be the first destination for current request logic we have distributed throughout controllers. They will have dependencies on other services for things like retrieving currently authenticated user, sending emails, etc.  However, they will depend on abstractions implemented under the `OpenCFP\Infrastructure` namespace.  There are awesome wins with this, particularly when it comes to authentication.  An application service for handling "Speaker" requests like "adding a talk" can use an implementation of an "AuthenticationService" that uses Sentry for web requests and for JSON API requests, use an OAuth implementation of AuthenticationService instead.  Meanwhile, client code for adding a talk doesn't change... all it cares about is getting the current authetnicated speaker for a given request and adding a talk to them (validating the request, of course).  This whole paragraph is best complimented by a simple diagram.

So, this is all "domain logic".  There are other parts of the codebase that I would consider "framework code".  `OpenCFP\Application`, `OpenCFP\Environment` and most-everything in the `OpenCFP\Provider` namespace are really there for bootstrapping Silex purposes.  I will include a section on how we have the Silex application organized.

In the future, the `ApplicationServiceProvider` will be used to register services like the speaker service referenced above, authentication service, whatever.  Will include more verbiage on this later.

**Comment by mdwheele** [comment]
Oh, something else that I think will be a good idea to set as a "standard" would be that anything that leaves the service layer should be treated as immutable.  In other words, a web controller shouldn't query for a `SpeakerProfile` and then start adding talks. That would mean that logic for adding talks has leaked into presentation areas of the application.  Having the object be treated as immutable (as there really is no benefit in actually trying to achieve an immutable PHP object... convention is good enough) means it can be serialized to different formats in a consistent manner across request gateways.  SpeakerProfile is currently perfect to send to Twig and have stuff "just work"... but it could be just as easy to add a `toJson` method and have pretty much all you need to represent the same speaker profile you see on the web as a json payload for the API.  Similarly applied to console gateway (though argument could be made at a point that presenter (speaker profile) shouldn't have knowledge on how to serialize to all those formats... I think it's fine here as rough notes)

**Comment by mdwheele** [comment]
Lastly should highlight the point that "service layer" is nothing special and the described abstractions above (having services for things like auth and all that) are really doing nothing more than isolating and distilling a bunch of Lego blocks you can more sanely test and trust; composing them to pull off / orchestrate behavior (responsibility of an "application service", a big wrapper for orchestrating use cases)

It has to be presented in a way that it's not overwhelming and also in a way that attracts new contribution. For example, when we implement auth to GitHub or else, it should be easy for a dev to contribute a new adapter. When we build an Ali endpoint from an existing service, it should be easy for someone to do another after a brief discussion of structure or formatting of Json bodies. 

This stuff should be easy and fun to work with. Not overly complex with no gain.

**Comment by chartjes** [comment]
Okay, so we're starting to veer off course here into a discussion on overall architecture for the application. I don't see anything IN PRINCIPLE that I disagree with here, but the first step is that we need to get a working API in place so people can make it easier to submit their talks to multiple OpenCFP sites.

At the highest level, we need a way for external apps to submit talks. I don't care if it's OAuth2 that we use (makes writing automated tests for it really annoying but such is life) but we need to pick something.

During the /dev/hell podcast last night I had an idea that I wanted to be able to have federated / distributed talk publishing. Imagine a button for a talk saying "publish it to another OpenCFP instance", followed by a screen where you enter the URL for the OpenCFP instance you want to use. They do the OAuth2 dance and now a talk from, say, TrueNorthPHP is not submitted for LoneStarPHP.

At a minimum we need the first thing done shortly (allow external app to submit talks) so that it's ready to go when Matt Stauffer's app is ready to go.

**Comment by mdwheele** [comment]
Agreed 100%. Made this issue in response to the suggestion in irc that there be a guide or "lay of the land" for things once everything settles so there's some "pie in the sky" here for sure. 

I think the idea you had is pretty badass and on mark for the biggest use case for the api. I posted an issue over on Matts repository regarding something similar. https://github.com/mattstauffer/savemyproposals/issues/33

**Comment by chartjes** [comment]
@mdwheele Can you please put this into a CONTRIBUTING.md file or close this issue out?

**Comment by mdwheele** [comment]
Can close for now. I can find time later no need for this to remain open as long as it's captured. I can reference later.
