### ISSUE TITLE
.htaccess in repo

### ISSUE THREAD

**Issue by zymsys** [opencfp/opencfp#193]
Could we reconsider having the .htaccess files in the repo? I would prefer supplying a distribution .htaccess file with a different name and adding something to the installation documentation about copying that suggested version and modifying it if needed.

Also, is there any reason for .htaccess files in both the root folder and the web folder? Can we pick one location and merge them?

I'd be happy to submit a PR for this if the idea is acceptable. If not I can just disallow htaccess in my apache config and put the required setup there - but maybe I'm not the only one who could face this problem.

**Comment by mdwheele** [comment]
Note also that the file in web is missing APP_ENV directive.

**Comment by mdwheele** [comment]
> Could we reconsider having the .htaccess files in the repo? I would prefer supplying a distribution .htaccess file with a different name and adding something to the installation documentation about copying that suggested version and modifying it if needed.

This makes sense if it buys anything for user. @chartjes will have to comment on what he feels the "installation experience" should be for a new user as he has the best grasp on who is using this and how they're using it. Theoretically, it makes sense though.

> Also, is there any reason for .htaccess files in both the root folder and the web folder? Can we pick one location and merge them?

Many shared hosts disallow the ability to specify Apache/Nginx document root path. Specifying document root at the `web` directory is safer than setting the document root at the root of the project. Both methodologies require `mod_rewrite`, which may also be disabled by particular shared hosts. So perhaps the argument for shared hosts is moot.

I believe it is simply a trade-off for **ease-of-use / installation** (for perhaps a developer that doesn't have much web server experience) at **the cost of** perhaps applying the application to a particular infrastructure. Chris should comment, but I think that a line of work that did anything with this should obviously make it dead simple as far as documentation. This type of thing would be pretty awesome to have as part of an automated installation process as well. (unrelated perhaps)

**Comment by pmeth** [comment]
My 2 cents:
1. project root should not be accessible so no need for .htaccess there.  @dustin I understand your point about different hosting companies, but we should not be catering to bad hosting companies, we should be encouraging users to leave them.
2. APP_ENV does not belong in .htaccess.  This should be configured by the server
3. The current .htaccess in /web is part of the front controller and is essential to the functioning of the application.  Thus it belongs in the project.  Someone should not have to rename it to install.  There is nothing in there that is specific to the environment.
4. I think we should consider using the Symfony standard .htaccess file (and probably renaming our index.php to app.php).  It accounts for a few more situations and is one less thing for us to worry about.

**Comment by mdwheele** [comment]
> 1. project root should not be accessible so no need for .htaccess there. @dustin I understand your point about different hosting companies, but we should not be catering to bad hosting companies, we should be encouraging users to leave them.

Agree, personally. Hypothesizing on reasoning here for having both. Chris can speak better to this, for sure.

> 2. APP_ENV does not belong in .htaccess. This should be configured by the server

Agree in scenario where user is knowledgable to do so themselves. We have opportunity to provide resources for transferring that knowledge at the cost of then maintaining that resource. Trade-off.

> 3. The current .htaccess in /web is part of the front controller and is essential to the functioning of the application. Thus it belongs in the project. Someone should not have to rename it to install. There is nothing in there that is specific to the environment.

This is arguably server configuration the same as environment variables. It's infrastructure-specific, for sure. I could make the same front controller directive as part of an Apache virtual-host or Nginx host configuration; negating the need for any .htaccess at all.

Anywho, pretty easy call to make. I still think it comes down to either specifying a reasonable default and setting expectation that folks should riff on it OR specifying no default and providing documentation for applying the project to a single / multiple infrastructure platforms (apache/nginx in this case).

**Comment by zymsys** [comment]
I'm going to make one more plea and then let it go. I have to disagree with Pete in that the .htaccess file is not part of the front controller. To me a front controller is software and a .htaccess file is configuration. The app's configuration is distributed in config/environment.dist.yml with instructions to copy this to config/environment.yml. It would be consistent with this to also provide a 'dist' version of the apache configuration.

This specific configuration is causing me trouble if I want to contribute to the project because it is not compatible with my environment which uses mass virtual hosting. I've been unable to work around the problem from httpd.conf so I'm stuck with a hack to swap in and out the distribution's htaccess file when I use git. If this is causing me problems it might cause other developers problems, and maybe that would be a good thing to improve.

End users will have to configure their web server and database server anyway. Copying a default configuration doesn't seem like too much to ask of end users.

That's my take on it. Chris, can you make a call to either:
* Leave things as they are
* Merge htaccess files into one .htaccess file located in the web folder
* Merge htaccess files into one 'dist' file and update docs to copy this into a production config

...unless there's some other even better option I've missed.

I don't mind submitting a PR once I know the direction Chris wants to take this.

**Comment by chartjes** [comment]
I think I like the idea of a htaccess dist file, seems like a good compromise

**Comment by mdwheele** [comment]
Distribution Apache config is good idea. I, too, come from an environment that uses virtual hosts rather than htaccess to configure this type of thing. My own virtual machine does the same. I am configured to not use the provided htaccess at all. 

However, this level of experience requires more ops experience than simply providing a distributable htaccess. I think merged or not is okay, but both must be equivalent in the baseline thy provide. For instance, both must specify application environment and a reasonable default should be chosen!

Thanks for your effort on this @zymsys

**Comment by yitznewton** [comment]
Looks like this is ready to close
