### ISSUE TITLE
Hiding names for anonymous initial abstract evaluation process

### ISSUE THREAD

**Issue by chrispecoraro** [opencfp/opencfp#206]
I hacked up opencfp to hide the names from the abstracts so that we can anonymous evaluate them.
If I add a toggle button to show/hide names, is it worth it doing a pull request for this?

**Comment by mdwheele** [comment]
Could you send a link to implementation? I think it depends on what "hacked up" looks like. Ideally this would be done at the service level as part of some DTO returned to be exposed by both web and API end points.

**Comment by chrispecoraro** [comment]
Again here I'm referring to the interface. I was thinking of a simple global toggle control which hides/shows "submitted by" names.

**Comment by chartjes** [comment]
Again, please send a PR to hide names from abstracts as a configurable option or else the issue might get closed

**Comment by chrispecoraro** [comment]
For my needs, I just commented out places in the template where the "submitted by" was showing. To do it properly, I would need a few days, that's why I was asking first if it would be useful. If you want, you can close this issue then I'll submit code when it's ready.
