### ISSUE TITLE
Removing flight/travel cost for online conferences

### ISSUE THREAD

**Issue by chrispecoraro** [opencfp/opencfp#207]
I hacked up openCFP to hide the travel information from the speaker registration when the conference is online.
Is it worth it to do a pull request for this? I'd have to figure out how it work it into the settings.

**Comment by mdwheele** [comment]
Could you send a link to implementation? I think it depends on what "hacked up" looks like. Ideally this would be done at the service level as part of some DTO returned to be exposed by both web and API end points.

**Comment by chrispecoraro** [comment]
I hacked it up for my own needs, but what I would do is actually write it in a proper way and then send the pull request. For the API, I'm not sure if it matters since interface designers could just use whichever information that they want.

**Comment by mdwheele** [comment]
Ah! I misread what this was was actually referring to. I thought it was directly related to the other issue you submitted re: anonymous abstract submissions. You're actually talking about implementation of variable account creation interface (front-end) display, correct?

If so, the fields related to flight/travel cost are already optional so having a configuration option for show/hiding fields on the registration (and all display) pages should "work", but it begs a larger question of handling variations in OpenCFP instances like this. If you have the free time to send a PR along, even if in raw form, it would be a good starting point for discussion. If not, I think this warrants more discussion than a simple boolean on/off? In other words, I see that type of implementation getting worked on sooner for something that handles more of the use-case. @chartjes has more experience with the types of modifications folks usually make to instances of OpenCFP. Perhaps he'll have some ideas on direction here.

That said, could you send along your idea in some rough form as part of this issue? Ignore what I said re: DTO+API. I misunderstood the issue as this seems purely front-end focused (show/hiding individual form elements)

**Comment by chrispecoraro** [comment]
There's not just to show. All I did was comment out wherever "submitted by" shows the name. Since I know most of the submitters to the online conference, I didn't want that to bias the selection. After we pick the winning abstracts, we'll then show the names. Since it's an online conference, flight/travels don't matter.

**Comment by chartjes** [comment]
@chrispecoraro Put together a PR and I'll take a look. Like @mdwheele mentioned we already have a configuration option for showing/hiding those fields and they are not considered required fields for validation purposes.

**Comment by chrispecoraro** [comment]
I must have not read through things well enough then. How can I disable flights/travel related information?

**Comment by chartjes** [comment]
Hrm, I don't see it in there either. Could've sworn that it was in there.

I would be happy to take a look at a PR that makes this possible

**Comment by chartjes** [comment]
I took an easy path and modified the template to hide those details if you set the 'online_conference' value in the config file to true. Thanks for the suggestion @chrispecoraro

**Comment by mdwheele** [comment]
Closing as it looks resolved. Thanks folks!
