### ISSUE TITLE
cost calculator

### ISSUE THREAD

**Issue by pmeth** [opencfp/opencfp#239]
use some sort of api maybe to get flight costs based on the user's airport and display in admin pages. this should probably even be elevated to the user level when they are configuring their profile, that way user can verify that we have the right airport.

would also like to see some sort of hotel cost calculator and maybe let the user configure their hotel stay.

these would be very helpful when calculating costs while making speaker selections.

**Comment by chartjes** [comment]
Closing due to lack of good freely-available airline and hotel stay API's
