### ISSUE TITLE
Remove truenorthphp branches

### ISSUE THREAD

**Issue by pmeth** [opencfp/opencfp#266]
To keep the main opencfp/opencfp repository clean & canonical, should we remove the truenorthphp branches? We have a copy of them on chartjes/opencfp, which is what we use to deploy anyhow.

**Comment by mdwheele** [comment]
It'd probably be good to clean out **most** of the remote branches and only leave ones that are long-running features that multiple folks are working on. Chris is just having the hardest time breaking old habits! :smile: /jk

Other branches are 1 year+ old.

**Comment by mdwheele** [comment]
What do you all want to do with this?

**Comment by chartjes** [comment]
Feel free to clean them out

**Comment by mdwheele** [comment]
I have cleared out all merged branches and truenorth branches. I left `ch-speaker-refactor` just to double-check that those 6 commits ahead aren't wanted before removing. I'll plan on cleaning that up a few days from now if there's no objection.
