### ISSUE TITLE
I started a wiki. Any objections

### ISSUE THREAD

**Issue by pmeth** [opencfp/opencfp#267]
Does anyone have any objections to me starting a wiki on this project?  I wanted to add a section for projects that are using OpenCFP to add a link and didn't have a good place to do that.  It seems like the only place to do that is in the README but it really looks like the README is getting too huge.

ps. I don't have a lot of experience with Github wikis. Do people have to send pull requests, etc, or can we make the access more broad for the wiki?

**Comment by michaelcullum** [comment]
In settings there is an option so either collaborators or everyone can edit. There are no pull requests but there is version control of sorts (more like revisions).

**Comment by pmeth** [comment]
ok. i would support letting everyone edit the wiki. unfortunately i don't think I have access to the settings for this project.

**Comment by mdwheele** [comment]
Yeah you can clone the wiki for a project from:
git@github.com:opencfp/opencfp.wiki.git.
No pull requests so unless you do anything else (which I'll describe
below), it comes down to shipping patches or "manual" pull requests via
email request, IRC or something.

For the projects at work where we want to open our wiki up to collaborators
within our Enterprise deployment of GitHub, we create an orphan branch on
the project repository called `gh-wiki` or something more clever. That
becomes the effective wiki commit history and folks can send PRs to that
branch. We then have automation sync `gh-wiki` to the actual internal wiki
repository. I bet you could do something similar, but abuse TravisCI to do
the work of syncing merged PRs to `gh-wiki` to it's actual repository on
GitHub :).

All that said, don't want to get in the weeds too much and distract the
conversation. I find with a lot of wikis that the information becomes stale
and unused if it's not in the direct pathway of development. That said, if
there WERE such a wiki, I would want to move a majority of what's in the
README into that and just leave like, "Hey, this is OpenCFP. It's a thing.
Here's how to install it and here's a lot more good information [link]." At
least this way, we could have more room above the cut for Grumpy propaganda
imagery.

On Mon, Nov 23, 2015 at 2:52 PM, Peter Meth <notifications@github.com>
wrote:

> ok. i would support letting everyone edit the wiki. unfortunately i don't
> think I have access to the settings for this project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencfp/opencfp/issues/267#issuecomment-159044569>.
>



-- 
Dustin Wheeler
Web Application Developer
College of Engineering, ITECS
North Carolina State University
Raleigh, NC 27695, x5-9786

mdwheele@ncsu.edu

Find my office with Google Maps:
http://go.ncsu.edu/find-dustin

**Comment by mdwheele** [comment]
`gh-docs` might be an appropriate branch name in this case as we'd be declaring the wiki as the official source of truth for all documentation (I would imagine) and start moving things there.

**Comment by mdwheele** [comment]
Hey @pmeth @chartjes, if you're interested, I've found an interesting way to be able to accept PR to a wiki using GitHub and Travis CI. You can see an example PR at the example repository https://github.com/mdwheele/wikidocs-example/pull/3. I can elaborate on this more if it's something we think we'd be able to take advantage of. Otherwise, was just an idea I ported from our work environment / GitHub Enterprise.

Workflow is pretty much the same. Send pull requests from topic branches on forks to `gh-wiki`. Travis is configured to deploy `push` events to a specific branch (`gh-wiki`). The deployment process involves giving Travis a deploy key to be able to push to the `.wiki.git` repository for a given project. Deploy script authenticates to GitHub via SSH and force pushes changes from `origin/gh-wiki` to `gh-wiki/master`. 

The idea is that once you put something like this in place, you don't touch the actual GitHub wiki anymore just as you wouldn't touch *any* deploy target in another system.

**Comment by chartjes** [comment]
I have no objections

On Tue, Nov 24, 2015, at 09:20 PM, Dustin Wheeler wrote:
> Hey @pmeth[1] @chartjes[2], if you're interested, I've found an
> interesting way to be able to accept PR to a wiki using GitHub and
> Travis CI. You can see an example PR at the example repository mdwheele/wikidocs-
> example#3[3]. I can elaborate on this more if it's something we think
> we'd be able to take advantage of. Otherwise, was just an idea I
> ported from our work environment / GitHub Enterprise.


> Workflow is pretty much the same. Send pull requests from topic
> branches on forks to gh-wiki. Travis is configured to deploy push
> events to a specific branch (gh-wiki). The deployment process involves
> giving Travis a deploy key to be able to push to the .wiki.git
> repository for a given project. Deploy script authenticates to GitHub
> via SSH and force pushes changes from origin/gh-wiki to gh-
> wiki/master.


> The idea is that once you put something like this in place, you don't
> touch the actual GitHub wiki anymore just as you wouldn't touch *any*
> deploy target in another system.


> — Reply to this email directly or view it on GitHub[4].


>



Links:

  1. https://github.com/pmeth
  2. https://github.com/chartjes
  3. https://github.com/mdwheele/wikidocs-example/pull/3
  4. https://github.com/opencfp/opencfp/issues/267#issuecomment-159466792

**Comment by chartjes** [comment]
Closed, wiki exists. Let's make sure we start using it.
