### ISSUE TITLE
Make a sweep through all tests and clean formatting / visibility of properties as necessary.

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#271]
Looking for stuff like this https://github.com/opencfp/opencfp/pull/270/files#r46741586 that isn't breaking the build by any means but is otherwise mostly style-related.

**Comment by chartjes** [comment]
@mdwheele Actually, can we close this or should I leave it assigned to you?

**Comment by mdwheele** [comment]
Leave it assigned. I really want to make a pass through this to make things more consistent.

**Comment by mdwheele** [comment]
I'm going to end up marking tests that interact with sqlite as I go through and clean property visibility as well so we have a clean way of beginning to corral.
