### ISSUE TITLE
Navigating to talk that doesn't exist throws a 500

### ISSUE THREAD

**Issue by eryno** [opencfp/opencfp#276]
## Steps to reproduce
1. Log in as an admin
2. Navigate to /admin/talks/<invalid_id> where ID is for a talk that doesn't exist; e.g. 10000000

## Expected behavior
The system will gracefully alert me that the talk doesn't exist.

## Actual behavior
The site returns a 500 error and an unstyled page.

**Comment by mdwheele** [comment]
@eryno: Jake sent a PR that resolves this issue like so:

![image](https://cloud.githubusercontent.com/assets/2453394/12026888/cff34698-ad8c-11e5-9549-36b8e9f986fc.png)

Gonna close this out. If you have any suggested changes, feel free to re-open and we can adjust. Thanks!
