### ISSUE TITLE
Navigating to speaker that doesn't exist throws a 500

### ISSUE THREAD

**Issue by eryno** [opencfp/opencfp#277]
## Steps to reproduce
1. Log in as an admin
2. Navigate to /admin/speakers/<invalid_id> where ID is for a speaker that doesn't exist; e.g. 10000000

## Expected behavior
The system will gracefully alert me that the speaker doesn't exist.

## Actual behavior
The site returns a 500 error and an unstyled page.

**Comment by mdwheele** [comment]
@eryno: Jake has submitted a PR that resolves this issue like so:

![image](https://cloud.githubusercontent.com/assets/2453394/12026902/f9bdfc34-ad8c-11e5-9c78-3121b62bda44.png)

If you have any suggested changes, please send them our way and we'll adjust.

Thanks again!

**Comment by eryno** [comment]
No suggestions; that looks great. I started trying to update it myself, but I'm not very familiar with Silex and I got distracted before I figured it out. Looking forward to reviewing Jake's PR and learning the Right Way to do it.
