### ISSUE TITLE
[Enhancement] Display airport name next to code

### ISSUE THREAD

**Issue by eryno** [opencfp/opencfp#280]
## Current behavior
A speaker's airport code is displayed as a link to a google search for flights to and from that airport. (Which is definitely pretty cool.)

## Suggested enhancement
Display the full airport name + city, state, and country next to the airport code in order to save reviewers a click.

**Comment by jsundquist** [comment]
There is an api for google flights which could possibly accomplish similar to what #239 was asking for.

**Comment by pmeth** [comment]
Here is an API I found https://developers.google.com/qpx-express/

However, I think to just display the airport name it would be better to just have a static list of airport codes.  Really, how often do they change? I believe I already have such a table someplace. I can add it as a migration to partially address this feature request.

**Comment by eryno** [comment]
I agree, @pmeth. Airport information can safely be in a table somewhere, along with location information (it's not always clear what city/country an airport is in just by the name).

**Comment by pmeth** [comment]
anyone who wants to implement this feature can continue on with the 280_airport-lookup branch. it basically just has a migration to add a table with a list of airports

**Comment by mdwheele** [comment]
I'd like to pick up initial work in doing a first pull, syncing it with new data, and exposing it to the rest of the codebase as a shared resource. Building the feature on top of that could be a continuance of that work.

**Comment by pmeth** [comment]
good by me. it would be useful in other places too i'm sure.

**Comment by mdwheele** [comment]
Where'd you pull this data from?

**Comment by pmeth** [comment]
don't rightly remember, but probably here: http://www.nationsonline.org/oneworld/IATA_Codes/airport_code_list.htm

**Comment by chartjes** [comment]
Closed because code for this issue got merged in

**Comment by mdwheele** [comment]
A migration that added a bunch of airport codes was merged, but nothing was written to expose any of that data to the web interface.

**Comment by chartjes** [comment]
Reopening

**Comment by mdwheele** [comment]
I'm about finished with my stab at this. Just hooking it up to the web interface now. Most of the problems I hit were to do with vendor-specific SQL that Sqlite3 did not play well with. Unrelated, some of the current migrations absolutely do not run or impartially run against Sqlite3. I'll be sending a separate PR for those.

**Comment by mdwheele** [comment]
All, What do you think of the following? Any advice on whether this can be improved?

![image](https://cloud.githubusercontent.com/assets/2453394/12368405/26fcb34a-bbb9-11e5-926c-be6b29cd0f36.png)

I've gotta put this on the individual speaker pages for consistency-sake, but otherwise have a PR ready to ship after some small fix-ups.

/cc @eryno @chartjes @pmeth @jsundquist

**Comment by chartjes** [comment]
Looks find to me -- better UX/UI is definitely needed for this app

**Comment by pmeth** [comment]
It looks fine though doesn't provide a huge improvement. Baby steps I
suppose. I say merge it in.

**Comment by mdwheele** [comment]
Alrighty then. I'll send a PR when I get back to a terminal. Got any ideas ahead of this as far as improvement. I saw the hotel/flight API reference for costs was closed for lack of good source of data.
