### ISSUE TITLE
What's the difference between Talks and Review Talks?

### ISSUE THREAD

**Issue by eryno** [opencfp/opencfp#284]
I can see there are some differences in functionality, but I'm curious what the overall rationale for these pages is. 

There's a lot of redundancy, and without help text, it's hard to tell when a user should load each, and where new features should go.

**Comment by eryno** [comment]
Also, I don't think I'm allowed to add one of those pink "question" labels, but if I were, I'd do that.

**Comment by jakefolio** [comment]
I'm not really sure the difference. It shows an aggregate of all the admin ratings and orders by best rated.
