### ISSUE TITLE
All talk rating (up/down vote) was removed

### ISSUE THREAD

**Issue by jakefolio** [opencfp/opencfp#285]
I recently rebased and found that all of the talk rating UI had been removed from Admin Talks page. As of the following hash: afdae85e1ee2fbbe66b93319498dc9a1fb8d316a, this UI was still there.

https://github.com/opencfp/opencfp/commit/afdae85e1ee2fbbe66b93319498dc9a1fb8d316a#diff-2dda05548a15dd6baf3c71e98c897bb2R25

*UPDATE*
This appears to be the point where a lot of work was reverted: https://github.com/opencfp/opencfp/commit/aafc9e5b201fd6ca52c6d999cad699a5b174b846

I'm assuming the submitter was not working off of an up to date version of OpenCFP when creating PR.

**Comment by mdwheele** [comment]
Resolved in #286
