### ISSUE TITLE
Tests need to be sorted out

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#307]
A :eyes: into 

* https://github.com/opencfp/opencfp/tree/master/tests/OpenCFP and
* https://github.com/opencfp/opencfp/tree/master/tests/unit

reveals

* test classes are using inconsistent namespaces
* some test classes do not even reside within a namespace
* some files declare multiple classes

I propose to 

* consistently use `OpenCFP\Test` as a namespace prefix
* pull out classes into separate files, following PSR-1

and then continue to sort out the existing tests.

**Comment by mdwheele** [comment]
Agree on namespacing tests though I'd like to hold off long enough to get a PR I'm working on in that improves coverage a bit; truthfully, for my own sanity in resolving conflicts. 

What do you think about mirroring the namespace of production code with expectation that there will be 1:1 match with production class to testcase? Reason I ask is it saves a number of imports in testcases. Really a matter of personal preference for me and the IDE handles most of it anyway so if there's a reason to separate, I'm down.

**Comment by chartjes** [comment]
I see we've done a bunch of merges related to this issue. @localheinz and @mdwheele, can we close this issue or is there more work to be done? If so, maybe we should break this done into smaller issues and actually assign them to people.

**Comment by mdwheele** [comment]
Honestly, an agreement that we start to merge tests into the `tests/OpenCFP` location rather than splitting would be good enough. 

> Any new tests must only be merged if applied under the `tests/OpenCFP` directory / namespace. There will be an ongoing effort to move remaining tests from `tests/unit` into that namespace. In addition, we value clarity in meaning / purposes behind tests. If there is excessive setup required for a test, it should be hidden behind a semantic (and possibly re-usable) method.

Any thoughts on the sentiments of that statement? I can draft a basic `CONTRIBUTING.md` to get us started.

**Comment by mdwheele** [comment]
Hahahahahaha... I never noticed this. Check out https://github.com/opencfp/opencfp/pull/261. I could have SWORE we added a basic `CONTRIBUTING` document. This was closed with un-merged commits. Want me to send another PR? It should be good to pull over, but is 300+ commits, 1 ahead of `upstream/master`.

**Comment by mdwheele** [comment]
I believe we've merged enough work against for right now. The tests are structurally in a better place and we're ready to continue work to improve coverage. Next steps for me will be to go through common duplicated boilerplate for tests that hit `Application` to execute a controller method and find ways of making that easier to work with. 

Ideally, we would find a way to isolate tests around controllers, but that is currently difficult considering quite a few things:

- Twig templates pose a problem in that they have global state dependent on Silex before middlewares having run. If the Twig Environment was simply fed a DTO of that global state derived from wherever, then we could simply stub it and wrap a nice API around that.
- Service doubles are sometimes tricky to get right. Thinking about Sentry here. If, instead, many controllers were relying on services, we could stub communication between objects at the API without having to dive down to implementation detail.

Anywho, thanks for helping with this. Let's keep the ball moving forward! :)

**Comment by localheinz** [comment]
@mdwheele 

Happy to help, it's been fun!
