### ISSUE TITLE
Tests in tests/unit need to be sorted out

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#308]
Using a :mag_right: in https://github.com/opencfp/opencfp/tree/master/tests/unit reveals

* test classes are not using namespaces
* test classes should probably live in `tests/OpenCFP`
* test classes declare multiple classes

I propose to 

* pull out classes into separate files, following PSR-1
* move classes into `tests/OpenCFP`

Related to #307.

**Comment by mdwheele** [comment]
Thanks for creating this @localheinz. What do you think about closing this one and taking this feedback to #307? Most of the thoughts I have apply to both :smile:

**Comment by localheinz** [comment]
@mdwheele 

:+1:
