### ISSUE TITLE
OpenCFP starts denying talk submission before CFP closes

### ISSUE THREAD

**Issue by michaelcullum** [opencfp/opencfp#336]
Note the time on https://github.com/opencfp/opencfp/blob/d0bac4cb822caacd0cd9d9f6067f3dd91ea71d0b/classes/Http/Controller/DashboardController.php#L49 vs https://github.com/opencfp/opencfp/blob/master/classes/Http/Controller/TalkController.php#L24

**Comment by mdwheele** [comment]
Should be fixed by #339. Thanks again!
