### ISSUE TITLE
Dedicated field for speakers to enter their joind.in url

### ISSUE THREAD

**Issue by michaelcullum** [opencfp/opencfp#350]
Lots of speakers exclude it or bury it or only include links in their 'more info' sections of talks which they've done before and include a link to a specific talk which is rather annoying when you want to see it in the context of all their talks.

Having a dedicated field for this would help encourage people to provide an easy to use joind.in link to their speaker profile (e.g. https://joind.in/user/chartjes)

**Comment by rocketpastsix** [comment]
I think this would be fun to implement, Id love to have a go at it.

**Comment by chartjes** [comment]
@rocketpastsix Feel free to do this up and submit a PR:

* Code changes
* DB migration to add the joind.in URL
* Tests to ensure everything works as expected

**Comment by chartjes** [comment]
@matthewtrask You still thinking of working on this?

**Comment by chartjes** [comment]
I see there is a URL field in the database schema that doesn't appear in the profile screen or the signup form. Maybe we could repurpose it for that
