### ISSUE TITLE
Tips/Documentation on setting up mail?

### ISSUE THREAD

**Issue by davethegr8** [opencfp/opencfp#355]
I'm trying to setup OpenCFP for CascadiaFEST 2016, but I'm having tons of trouble getting email to work. Is there any documentation or tips for setting up a mail server? Or any example configs that could be shared to give me a starting point?

Thanks!

**Comment by pmeth** [comment]
Here is my config for mailgun which is working

$tail -n7 production.yml

mail:
  host: smtp.mailgun.org
  port: 587
  username: do-not-reply@cfp.myfancyconference.com
  password: "a1b2c3d4"
  encryption: tls
  auth_mode: ~

**Comment by davethegr8** [comment]
Thanks, that's helpful. :smile: 
We are running OpenCFP on a VPS where we have access to anything we want to install, so would it make sense to have some way to use php's native `mail()`? I'm not sure that's something I have the bandwidth to address right now as part of our rollout, but it could be a later thing I or someone else could look into.

**Comment by pmeth** [comment]
This is using SwiftMailer which does everything mail() does plus a bunch more. I see no reason why you would want to switch to a less flexible solution.

I'm not sure I understand your comment about installing stuff.  Everything you need can be installed with `composer install`.

**Comment by davethegr8** [comment]
Oh, I meant I can `apt-get install postfix` if we need to, that was all.

I guess that I'm not getting why setting up another 2nd party service is necessary--unless there's ton's of features you get through Mailgun et al that are hard to setup/maintain on your own. I'm decent at LAMP sysadmin but my experience seems to stop just before email admin, so much of this is just my ignorance on how to proceed. 

I'm assuming I could setup SwiftMailer to go through our server if I wanted to. I was having trouble setting things up last night, and couldn't connect the SwiftMailer docs to what OpenCFP was doing. :grimacing: That's why I was asking for documentation or examples.

We're going to use Mailgun also (and it's working now), so thanks so much for your help. :facepunch: (read that as 'fistbump')

**Comment by pmeth** [comment]
Just to clarify Mailgun has nothing to do with OpenCFP, it's just who I happen to be using for my email service. It's a good option for this use case, but if you have another email service you use, such as Gmail or your ISP, you can just configure their SMTP settings in the appropriate config file (`production.yml` for example).

The built in mail() function in php normally uses sendmail which will send mail directly from your server. I find these days it is pretty hard to stay off spam lists when sending mail directly from your server, so SMTP is a better option as you can use authenticated, recognized mail servers.

Even though I don't think it is a great idea, if you really wanted to add sendmail functionality, SwiftMail does support it.  You should be able to get it working by adding a line to `classes/Application.php` right after the SwiftmailerServiceProvider registration.  Something like this maybe:
```
        if ($this->config['mail.transport'] == 'sendmail') {
            $this['swiftmailer.transport'] = $this->share(function () {
                return new \Swift_SendmailTransport();
            }
        }
```
and then add a line to your config under the mail section `transport: sendmail`

Note I haven't tested this, just talking in theory.

**Comment by davethegr8** [comment]
I may give that a shot in the future. Thanks for all your help!
