### ISSUE TITLE
[RFC] Support a single sign on system

### ISSUE THREAD

**Issue by patkar** [opencfp/opencfp#384]
# Expected Result

So much conferences uses OpenCFP, so it would be cool to support single sign on between all those instances. And pulling all the profile data from. A simple OpenID login my suffice but it has not the profile data. Maybe could use SymposiumApp as login provider where the speaker profile is pulled of too.

Additionally you could pull a talk from e.g. SymposiumApp automatically too.
# Actual Result

At the moment I have to register over and over again on every conference.

**Comment by chartjes** [comment]
HI @patkar, sorry for the huge delay in getting back to you. I have to replace the auth/permissions library I'm using first before something like this can be implemented.

I had hoped that SymposiumApp could be some kind of central authority but it looks like development has slowed on the project so I am not sure where that leaves OpenCFP

**Comment by patkar** [comment]
@chartjes Maybe a central (modified) OpenCFP instance where you put profiles and all CfPs and it acts as a SSO provider/IdP and the OpenCFP instance of the conference can pull the bio and talks on click? IMHO like SymposiumApp but realised with OpenCFP.

**Comment by heiglandreas** [comment]
I'd split that into two parts:

* One being the SSO part. Using a library like [hybridauth](https://github.com/hybridauth/hybridauth) or [socialConnect](https://github.com/socialConnect/auth) that should be doable so we can use a third-party provider for login.
* The second part would  be the possibility to pull in informations from a third-party like Symposiumapp or an OpenCfP-SaaS.

Having Symposiumapp/OpenCfP-SaaS also as a Login-Provider would be the best, but IMHO that could be split up.

**Comment by mdwheele** [comment]
It's not too much to integrate Sentinel with https://github.com/laravel/socialite.

**Comment by chartjes** [comment]
So the *other* thought I have is a paid add-on for OpenCFP that handles both SSO (using a centralized service as the OAuth end point) and allows people to see records of what talks they submitted to OpenCFP instances that are using the plugin. The app would be modified to send data to the centralized service every time a talk was submitted.

That way people could create just one account with the OpenCFP "hub" and it would be used to log in to any instance that has the add-on in place.

I guess it depends on whether or not people feel bad about me trying to make money off of the app. ;)

**Comment by heiglandreas** [comment]
There currently is also an idea of creating something similar not only for OpenCFP. You might want to have a look at https://gist.github.com/liam-wiltshire/5c7e311f4cae1d7890a03715d371dd38 - though that might interfere with your plans to make money off it. Or we might need to share ;)

**Comment by mdwheele** [comment]
Looks like more people need to check out https://symposiumapp.com. Seems to pull a reasonable representation of CFPs and also allows crowdsourcing of the data. It's focus is on speakers. It does little to nothing for organizers other than advertisement. 

A fundamental problem with all of these different sources is that they are all attempting to niche into a different part of the conference organization domain. There is a real opportunity for abstraction to either integrate all of these services together or obsolete them through consolidation. 

I've been contemplating stepping into this space in the open; be it through expansion of OpenCFP scope (which would require conversation) or something else entirely. With regard to charging for any of this, I'm a firm believer in appropriate compensation. That said, outside of server costs for a centralized multi-tenant SaaS, I don't see much reason to charge. Unless that application also stepped into registration and began taking money. Even then, I personally like the idea of open source, yet hosted for convenience.

**Comment by heiglandreas** [comment]
Symposium pulls the CfPs from joind.in and that's it. No other sources of CfPs. It's main aim is to have a central repository for speakers talks and bios. Along with pronto it allows speakers to easily add talks to a CfP. 

The idea described in the gist is to allow speakers also to have a central repository where they can see what they submitted to what conference - without needing a single backend on the conf-site. So it's not thought as a replacement for existing tools but as an addon for speakers that's currently not existing.

Besides symposium there's also papercall.io which is an SaaS aimed at Conference-Organizers to ease their live. But they do not crowdsource their data as it's a paid service from a certain point on.

**Comment by heiglandreas** [comment]
And besides papercall.io (SaaS for conf-organizers) and sympsoiumapp.com (Talk and Bio-repo for speakers) there's callingallpapers.com which aims to list all currently open CfPs from different sources. Currently joind.in and Lanyrd are covered. Papercall.io (most of them are already on Lanyrd)  and the PHP-Website are at the moment "in the making" and as it's extensible every other website can be added as well provided someone is writing a parser…

And it's also possible to add single confs via the API so having a "publish to CallingAllPapers" in OpenCFP would be no problem…

**Comment by mdwheele** [comment]
Ah, I see. I was considering Symposium itself as a source in addition to Joind.in which is just an adapter. 

Looking at https://symposiumapp.com/conferences/create

They claim to want to support more con management features in the future. Just tacking more info here.

**Comment by pmeth-delvia** [comment]
Not to be a sourpuss, but is this the best place to discuss whether, or how to make money from opencfp? I certainly don't have a problem with money, but I feel the open-source repo should simply add functionality. If someone wants to use that functionality to make money, that's up to them.

**Comment by mdwheele** [comment]
Agreed

**Comment by chartjes** [comment]
BAH

**Comment by chartjes** [comment]
Closing as OpenCFP 2.0 is moving towards SSO via Github/Facebook/Twitter/OpenCFP Central
