### ISSUE TITLE
Default sort order on talk review page

### ISSUE THREAD

**Issue by davethegr8** [opencfp/opencfp#391]
Quick question / quirk:

In [/classes/Domain/Entity/Mapper/Talk.php](https://github.com/opencfp/opencfp/blob/master/classes/Domain/Entity/Mapper/Talk.php#L156) the default sort order for the Review Talks page (aka top rated) seems to be `ORDER BY rating DESC, total_rating DESC`. Is this intended? Wouldn't that make the first vote for any given talk be the primary sort condition?

We're seeing an unexpected order of talks on this page and I suspect it's because of this.

One caveat of our usage however, we modified the review page to include all votes (+ and - 1s) where normally that page would just have the `WHERE rating = 1` clause, we have `WHERE rating != 0`

# Steps required to reproduce the problem

1. Get Bunches of talk submissions
2. Get a bunch of votes on talks by admins
3. Go to the top rated page

# Expected Result

* Talks are listed from top to bottom depending on what their final vote totals are

# Actual Result

* Talks are listed out of order

**Comment by davethegr8** [comment]
Yeah, it's `/admin/review` with `<h2 class="headline">Top Rated Talks</h2>`

**Comment by pmeth** [comment]
so whoever does a fix should also make the naming of the Menu and the Heading the same.
