### ISSUE TITLE
Installation video

### ISSUE THREAD

**Issue by Incognito** [opencfp/opencfp#394]
This isn't a bug, but something I think would be useful for the README file

I recorded a video to help a friend install the project, it's perhaps not ideal for everyone but if this is a good thing to have in this project and something I can get some feedback on (eg, too long, skip specific parts, cover other parts etc) I can re-record this without wandering through mysql install screens.

[![asciicast](https://asciinema.org/a/8mqwrrjvh47plh5yzoubolkkl.png)](https://asciinema.org/a/8mqwrrjvh47plh5yzoubolkkl)

**Comment by chartjes** [comment]
@Incognito 

The installation instructions have recently changes with a contribution from @jakefolio. Yesterday I did an install and rearranged things slightly in the README.md file to reflect those changes.

If you want to make a video of you going through an install following the directions I would be happy to embed the video in the README file.
