### ISSUE TITLE
New Logo?

### ISSUE THREAD

**Issue by elioqoshi** [opencfp/opencfp#405]
Hey guys,

Great stuff you are doing! I'm from Ura Design and love Open Source Design :)
I'd love to help you out with a new logo in case you are looking to update it. 
What do you think?

Some of my work can be found on Dribbble:
https://dribbble.com/elioqoshi

**Comment by chartjes** [comment]
Hi @elioqoshi, my apologies for such a long delay in responding. I'd love to see your ideas for a new logo.

**Comment by elioqoshi** [comment]
No worries! I will try to come up with something

**Comment by elioqoshi** [comment]
@chartjes Sorry, this somehow got lost. Are you still up for that?

**Comment by chartjes** [comment]
@elioqoshi I am, I am just going through issues and closing ones that seem dead or do not fit what I, as Dictator For Life, want to see for the project ;)

**Comment by elioqoshi** [comment]
![draft-01](https://user-images.githubusercontent.com/5436686/31319022-f06e98f8-ac5b-11e7-99c6-c631a8708097.jpg)

Gave this a go, made it icon friendly and had a go at the Zilla font which is also an open font (used by Mozilla)

What do you think?

**Comment by chartjes** [comment]
@mdwheele What do you think?

**Comment by mdwheele** [comment]
I think it's pretty badass. Any chance you have it as an SVG? 😄

**Comment by elioqoshi** [comment]
Sure! If you want to go with this, I can export it for you in SVG and PNG in horizontal, vertical, color, black and white versions :)

**Comment by mdwheele** [comment]
@elioqoshi I've started incorporating this into some UI work I'm playing around with. Don't mean to push (no rush) but if you get a chance to export the SVG, lemme know! Specifically, I think I only need the icon. Coloration can be done via CSS depending on how the SVG paths/layers get exported. Was able to bring in Zilla Slab via Google Fonts.

**Comment by elioqoshi** [comment]
@mdwheele here we go mate!

https://github.com/uracreative/works/tree/master/openCFP

Let me know if you need anything else and what Copyright/License notice I should put into the folder.

**Comment by mdwheele** [comment]
The project is [MIT licensed](https://github.com/opencfp/opencfp/blob/master/LICENSE.md) but I don't know if that requires that artwork be licensed that way. As long as the licenses are compatible, I think the decision is yours to make, as the contributor. That said, I am no lawyer 😄 

@chartjes do you have any advice re: licensing?

**Comment by elioqoshi** [comment]
I am fine with Public Domain CC0 but you should use anything between CC0, CC BY or CC BY SA :)

**Comment by elioqoshi** [comment]
Also as a contributor I happily transfer the logo rights to you, as the openCFP maintainer

**Comment by mdwheele** [comment]
Hey @elioqoshi. Did a bit of research and CC0 looks good to me. I've also been playing around with design ideas and incorporated this into those. I figured you'd be interested in how the work's applied. Thanks again for the new logo. Looks great!

**Before**
![image](https://user-images.githubusercontent.com/2453394/31573896-4adc65f6-b092-11e7-8d64-559476032245.png)

**After**
![image](https://user-images.githubusercontent.com/2453394/31573887-26114502-b092-11e7-8e12-ff4079d17f9f.png)

**Comment by elioqoshi** [comment]
That looks indeed great! Happy I could help
