### ISSUE TITLE
[Enhancement] Allow filtering by talks I have not rated

### ISSUE THREAD

**Issue by eryno** [opencfp/opencfp#431]
## Current Behavior

On the talks page (/admin/talks), one can filter by "Rated" and "Unrated" talks, but it appears to check whether anyone has ever rated a talk. There is no way to filter by talks that *I* have rated/not rated.

## Suggested Enhancement

Either:
 a. Add a filter for "Unrated By Me"
 b. Change the current "Rated"/"Unrated" filters to only look for ratings by the currently logged in user, since that is a vastly more useful use case. I'm having a hard time picturing why you'd want to see if *anyone* had rated/not rated a talk.

**Comment by carnage** [comment]
I consider this a bug - it's the query that's wrong imo see: https://github.com/opencfp/opencfp/pull/429

**Comment by jsundquist** [comment]
@chartjes I think this can be closed with @mwillbanks merge request of #429 .
