### ISSUE TITLE
Unable to insert new OpenCFP\Domain\Entity\TalkTag - Errors: array ( )

### ISSUE THREAD

**Issue by akrabat** [opencfp/opencfp#443]
# Steps required to reproduce the problem

1. Try to submit a new talk to https://opencfp.phpkonf.org
2. 
3. 

# Expected Result

* See a thank you page / returned to list (can't remember what the success case is)

# Actual Result

* See a white page with the text `Unable to insert new OpenCFP\Domain\Entity\TalkTag - Errors: array ( )` at the top. 
* Note that the talk appears to have submitted correctly as manually navigating to https://opencfp.phpkonf.org/dashboard shows the talk on the list.

**Comment by anshul35** [comment]
Getting the same error! Any ideas on how to fix it?

**Comment by andrewwoods** [comment]
I'm getting this too! haven't looked into the cause yet though.

**Comment by chartjes** [comment]
Closing because I have removed tags from being part of talks, will eventually add in a migration to drop the impacted tables as well.
