### ISSUE TITLE
Fatal error: Call to undefined method OpenCFP\Console\Application::getContainer()

### ISSUE THREAD

**Issue by nb** [opencfp/opencfp#446]
# Steps required to reproduce the problem

1. Run a CLI command, like `bin/opencfp cache:clear`

# Expected Result

* “[OK] Cleared caches.”

# Actual Result

* `Fatal error: Call to undefined method OpenCFP\Console\Application::getContainer()`.

It looks like this was broken by #438.

**Comment by emir** [comment]
Same here

**Comment by chartjes** [comment]
Fixed in the latest master

**Comment by localheinz** [comment]
Ha, sorry about that one!
