### ISSUE TITLE
Clean up end date code - add support for time & timezone

### ISSUE THREAD

**Issue by pmeth-delvia** [opencfp/opencfp#450]
# Steps required to reproduce the problem

1. Be a developer who cares about dates and times
2. Grep the codebase for how `enddate` is used (https://github.com/opencfp/opencfp/search?utf8=%E2%9C%93&q=enddate)
3. Hang head in shame

# Expected Result

* consistently use the enddate config value and ideally manage it in a central place
* support a timezone in enddate
* support a time as well if someone wants to end at 5pm or something

# Actual Result

* in some places the code uses strtotime with 11:59 appended, other places new DateTime objects are created without time
* there is no way to specify a timezone without breaking the code
* no way to specify time without breaking code

**Comment by heiglandreas** [comment]
Shouldn't removing the ```11:59``` in the code and moving it over to the config file be sufficient? From what I read so far the string given in the config is passed to DateTime and that should then also be able to handle a string containing a time. It should also be possible to add an offset in there… - That'd be for a quick-fix…

**Comment by heiglandreas** [comment]
The timezone can be [set in the configuration](https://github.com/opencfp/opencfp/blob/master/config/production.dist.yml#L15) and will then be used as [default timezone](https://github.com/opencfp/opencfp/blob/master/classes/Application.php#L55)

That timezone will be used for the complete CfP.

**Comment by pmeth-delvia** [comment]
@heiglandreas agree on removing the 11:59 from code so that you can put any valid DateTime string in the config.  The only thing is the way humans think, when they omit the time (for example 2017-02-28) they are implying the end of the day (eg 2017-02-28 23:59:59), yet when php encounters an omitted time, it interprets as the beginning of the day (eg 2017-02-28 00:00:00), so we would need some additional logic to handle that case. Also, we should look at how this translates in the templates. I believe right now it simply uses the unchanged config value, which maybe is ok.

Thanks for pointing out the timezone in the config. i must have a config from an older version which didn't include that, but i noticed my .dist file has it.

**Comment by heiglandreas** [comment]
I'm currently in the process of "fixing that mess". Have a look over at https://github.com/heiglandreas/opencfp/tree/hotfix/DateTime  

As soon as it's ready I'll open the PR
