### ISSUE TITLE
[Refactor] Use Symfony Security Component

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#454]
The current authentication and authorization library is Sentry, which is no longer maintained. I want to move to using the Symfony Security component due to easy integration with other parts of the application.

It's a big task that touches pretty much every part of the application and will also require fixing tests that are using Sentry.

Any volunteers to help me?

**Comment by enygma** [comment]
I'd help out if I knew the Symfony Security component very well. The extent of my knowledge comes from reading about it, not really putting it to practical use.

Maybe @skoop could help out a bit?

**Comment by skoop** [comment]
I would recommend simply using FOSUserBundle for that. It is well-documented and offers just about any feature you'd want for authentication and authorization. I don't know Sentry, so I don't know the migration path.

**Comment by chartjes** [comment]
FOSUserBundle looks pretty good, thanks for the tip.

**Comment by zanderbaldwin** [comment]
I don't think FOSUserBundle would work with a Silex application, but it's a good starting place for ideas.

**Comment by skoop** [comment]
ah, sorry, I had not dug into OpenCFP enough to realize it was a Silex app, not a Symfony app. I believe there was some documentation on how to do authentication in Silex, let me find it.

**Comment by skoop** [comment]
http://silex.sensiolabs.org/doc/2.0/cookbook/guard_authentication.html is the one I had in mind. While aimed at API authentication, it could also easily be applied to web apps.

**Comment by chartjes** [comment]
Closing because I decided to go with Sentinel from Cartalyst -- once I did all the DB schema changes it was been almost a drop-in replacement
