### ISSUE TITLE
[RFC] Combine first name and last name into one field

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#456]
Been thinking that it makes sense to only have one name field. The only potential problem I see is that if we ever decide to do sorting in the lists of talks by last name, we lose that ability.

Thoughts?

**Comment by jsundquist** [comment]
What would be gained by combining them together?  If you are looking at exporting them to a service like joind.in, then combined makes sense. If its just for the sake of combining them, no I don't think it makes sense. I see a larger benefit to keep them separate.
