### ISSUE TITLE
[SSL] Forms URLs are rendered using http instead of https

### ISSUE THREAD

**Issue by davsket** [opencfp/opencfp#463]
I'm new to PHP, but haven't found a way to change urls to work with HTTPS instead of HTTP.

# Steps required to reproduce the problem
1.  Configure your server to use HTTPS
2. Configure production settings to use `url: https://yourdomain.com` and `secure_ssl: true`
3. Go to your site at: `/signup` and the form is pointing to HTTP, all website links are pointing to HTTP too.

# Expected Result

* Forms and other links should point to HTTPS

# Actual Result

* Forms and other links should point to HTTP

**Comment by chartjes** [comment]
Hi @davsket -- I haven't set it up to use SSL before but I have asked some other folks who've done it to check things out for me

Tagging @localheinz and @mdwheele

**Comment by jakefolio** [comment]
It should be forcing all routes to SSL:
https://github.com/opencfp/opencfp/blob/b5d2250c83cc7d878e008bff8b8649966987c696/classes/Provider/Gateways/WebGatewayProvider.php#L45

Can you set secure_ssl locally and see if it forces SSL routes there?

I want to make sure your production environment is set and looking at the right config.

**Comment by robertbasic** [comment]
I have just tried to reproduce the issue reported.

I created a self-signed certificate on my localhost, restarted nginx, set `secure_ssl` to `true` in the configuration file.

Everything seems to work OK, all forms are submitted through HTTPS, all links are HTTPS.

I believe this issue can be closed as there's nothing wrong with OpenCFP.

@davsket did you figure out the problem in the end? Or do you still have problems with this?

/cc @chartjes
