### ISSUE TITLE
[Enhancement] Extend session time

### ISSUE THREAD

**Issue by andrewwoods** [opencfp/opencfp#468]
# Steps required to reproduce the problem

1. Login to the CFP site
2. Work on something else for a while - say, for 1 hour
3. Return and Click the dashboard link.

# Expected Result

* You will remain logged in
* I'd like to have a configurable session timeout value, _in the number of seconds_, in your configuration **.yml** file

# Actual Result

* Your session is terminated, and you need to login again

**Comment by chartjes** [comment]
Pretty sure this can be done via php.ini to extend the session life. Does not strike me as something that needs to be in OpenCFP itself
