### ISSUE TITLE
problem sending emails from app

### ISSUE THREAD

**Issue by DarGrze** [opencfp/opencfp#480]
Despite a proper config as shown in README, OpenCFP don't want to send any email form app. The config yml in "mail" section is:

> mail:
  host: smtp.mailgun.com
  port: 587
  username: no-reply@mg.some.domain
  password: "here_is_a_proper_password"
  encryption: tls
  auth_mode: ~

I've tried the same with my own localhost (Postfix) to check whether my problem derives inside or outside the app. In this case config looks like:

> mail:
  host: localhost
  port: 25
  username: root
  password: ~
  encryption: ~
  auth_mode: ~

Unfortunately, still the same effect: no emails, no entries in local maillog and no errors in the app.log.
OpenCFP was installed step-by-step with README. Help me please.

**Comment by chartjes** [comment]
Well, this is awkward.

Somewhere along the line we removed the code that sends user activation emails. That's why you weren't seeing any emails. I will add it back in, test it, and let you know when it's all working correctly. My apologies.

**Comment by DarGrze** [comment]
Thanks a lot for so quick reaction! It's as important as we'd like to start our cfp in a days. Feel invited, of course ;)

**Comment by chartjes** [comment]
@DarGrze, by default we automatically activate the account so people can log in right away.

Would you like me to just simply modify the email to confirm they signed up for an account? I would need to write some new code to have an account activation end point and I don't think I could get that done in a day.

**Comment by DarGrze** [comment]
Ok, take it easy. It works without emails, so this functionality is also ok. You just helped me a bit, cause I know the problem isn't only by my side. So, thanks for now :)

Cheers,
-- Darek.

-- 
Sent by Kaiten Mail.

**Comment by chartjes** [comment]
Closing this issue then
