### ISSUE TITLE
Internal Server Error when viewing my own submitted talk after submissions were closed.

### ISSUE THREAD

**Issue by brettshumaker** [opencfp/opencfp#483]
# Steps required to reproduce the problem

1. Submit a talk.
3. Attempt to view talk from your dashboard (https://domain.com/talk/{talk_id})

# Expected Result

* It's expected to be able to view talk.

# Actual Result

* Internal server error.

I tried to debug this a little bit and I tracked it down to the `loadTemplate()` method in `vendor/twig/twig/lib/Twig/Environment.php`. The eval'd code that creates the class for that template at line 462 is where the error is occurring I think.

Any help is appreciated.

**Comment by chartjes** [comment]
Hey Brett, I am moving house and don't have home internet yet. Once I am set up I will take a look, thanks for the bug submission.

**Comment by brettshumaker** [comment]
No worries. I know how that is.

Just updated my original post to clarify the steps to reproduce. Also confirmed that viewing the talk in the admin functions properly (https://domain.com/admin/talks/{talk_id}).

I'm having someone else take a look as well in the mean time. Thanks again!

**Comment by brettshumaker** [comment]
Disregard. Apparently we had added a custom field to the talk form and didn't have it registered in all the correct places. Removing it fixed the error. Problem exists between keyboard and chair. 😄
