### ISSUE TITLE
Request for feedback: Improve review mechanism

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#485]
We would like to use OpenCFP for the Dutch PHP Conference, but are considering developing features for reviewing/rating talks.

- Adding a reviewer role, who would have limited access to the dashboard
- Adding a rating system based on a 1-10 score.
- Adding an overview of the talk scores for the admin.

Some of these ideas were mentioned earlier in #415. This isn’t quite the same idea as #484, as this would be a ‘private voting’ so to speak. This also won’t require any hooks with external ticketing systems.

Would such a feature be of any value to OpenCFP? And if so, any feedback on how to approach the goal of making rating/reviewing talks in OpenCFP easier is very welcome!

**Comment by chartjes** [comment]
@BackEndTea I do have a long-running refactor where I am moving the app to Sentinel from Sentry for authentication purposes and had implemented the idea of having users who were reviewers but not admins.

I am not sure of the scope of work to add a rating system to replace or sit next to the existing one. I certainly don't object to seeing such a thing built on top of the existing system, but I seem to have gotten bogged down in the refactor of the auth system and have no end date in sight.
