### ISSUE TITLE
E-Mail to Speakers

### ISSUE THREAD

**Issue by tobru** [opencfp/opencfp#487]
It would be great if E-Mail messages could be sent to the speakers from OpenCFP, f.e. if a proposal has been accepted or declined.

**Comment by chartjes** [comment]
Hi @tobru,

If I am understanding your enhancement request, you would like to see something like:

* email everyone who has a talk that was labelled as "accepted" with "your talk has been accepted"
* email everyone who has a talk that was not accepted a rejection email
* create editable template for the acceptance email
* create editable template for the rejection email
* add admin feature for activating this feature

**Comment by tobru** [comment]
@chartjes You got it exactly as I imagined this feature! 🎉

**Comment by chartjes** [comment]
Closing as this is a planned feature of OpenCFP Central

**Comment by tobru** [comment]
@chartjes What is "OpenCFP Central"?

**Comment by chartjes** [comment]
@tobru A planned centralized app that will allow for SSO for other OpenCFP instances running v2 of OpenCFP and paid reviewing tools (including ability to email speakers and submitters)

**Comment by matthewtrask** [comment]
@chartjes when is this happening? Would love to use it for Southeast PHP.

**Comment by chartjes** [comment]
Probably won’t start working on it until March.
