### ISSUE TITLE
[RFC] Refactor from using Spot to Illuminate

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#506]
As I look at the upcoming refactor from Sentry to Sentinel, I notice that it natively supports working with illuminate/database. It could be easier to integrate other libraries and tools into OpenCFP if we support illuminate/database

**Comment by mdwheele** [comment]
👍 for Eloquent. Behind that 100%.

**Comment by BackEndTea** [comment]
I'm playing around a bit with this, and i'm wondering, would it be better to simply call the static models like this:
```php
$users = User::all();
```
Or if its better to load the models from the container so we can do this:
```php
$users = $this->service(User::class)->all();
```
And have some kind of Model provider that looks a bit like this
```php
public function register(Container $app)
    {
        $app[Favorite::class] = function ($app) {
            return new Favorite;
        };

        $app[Group::class] = function ($app) {
            return new Group;
        };

        $app[Talk::class] = function ($app) {
            return new Talk;
        };

        $app[TalkComment::class] = function ($app) {
            return new TalkComment;
        };

        $app[TalkMeta::class] = function ($app) {
            return new TalkMeta;
        };

        $app[User::class] = function ($app) {
            return new User;
        };
    }
```

And on another note, this is probably a good chance to up code coverage as this and #498 will require a decent amount of refactoring.

**Comment by mdwheele** [comment]
I wouldn't do service lookup on Eloquent models. For such a relational model, calling them directly would be fine, I think. That said, it wouldn't be unreasonable to continue the use of things like `SpeakerRepository`.

**Comment by mdwheele** [comment]
Left this on a related PR but it's probably more relevant here:

> Another thing to consider is "Why do we 'own' models for things related to a specific authentication library?" We should probably delegate to Sentinel through Authentication or AccountManagement rather than keeping our own. I'd say the same for Phinxlog, but I'm not entirely sure of callers right now.
> 
> As far as the model goes, I would like to see a lot of the functionality related to speakers behind a Speaker or User model (e.g. submitTalk, updateProfile, etc.) to avoid things like are in the current TalksController where we kinda hit the model from the side to create a Talk from thin air. This would also encapsulate a lot of the permissions checks we currently do in controllers (e.g. all the checks for User id matching to make sure you are authorized to edit Talk entities)

**Comment by BackEndTea** [comment]
@mdwheele I changed one controller to work with Models, and the nice thing about working with the provider is that you can easily mock them out. Which becomes a bit more difficult with static calls.

> Another thing to consider is "Why do we 'own' models for things related to a specific authentication library?" We should probably delegate to Sentinel through Authentication or AccountManagement rather than keeping our own. I'd say the same for Phinxlog, but I'm not entirely sure of callers right now.

I agree on this one, thats why i didn't make a model for the Phinxlog and a few other items. That and the fact that it doesn't get used anywhere.

> As far as the model goes, I would like to see a lot of the functionality related to speakers behind a Speaker or User model (e.g. submitTalk, updateProfile, etc.) to avoid things like are in the current TalksController where we kinda hit the model from the side to create a Talk from thin air. This would also encapsulate a lot of the permissions checks we currently do in controllers (e.g. all the checks for User id matching to make sure you are authorized to edit Talk entities)

Depending on how much functionality we move to the models it might be better to use a Repository pattern or something alike, to make it easier to switch in the future. And maybe apply some kind of caching down the line.

**Comment by mdwheele** [comment]
> I changed one controller to work with Models, and the nice thing about working with the provider is that you can easily mock them out. Which becomes a bit more difficult with static calls.

Gotcha. I agree with the idea, just at a different level of abstraction. Rather than putting every AR model in the container, I would prefer to put "application-owned" *access* to the model in the container. Basically explicate support entry-points of the model and once retrieved, let callers navigate freely, but I never expect to be able to get `TalkComment` from the container. I would instead grab `Talk::find(1)->comments()` (as a over-simplified example).

**Comment by mdwheele** [comment]
Hehe, also, I don't mean to come across as bike-sheddy. I say we open a PR and work it 😄
