### ISSUE TITLE
[Enhancement] Use trusted_proxies

### ISSUE THREAD

**Issue by sybix** [opencfp/opencfp#521]
# Steps required to reproduce the problem

1. Deploy opencfp with a ssl reverse proxy, with x_forwarded_proto enabled
2. Enable secure_ssl

# Expected Result

* Correct loading of the app

# Actual Result

* Infinite redirect because of the x_forwarded_proto header not trusted

For now i have added this to index.php

```
use Symfony\Component\HttpFoundation\Request;

Request::setTrustedProxies(array($ip));
```

It would be nice if it is a paramer in production.yml

**Comment by chartjes** [comment]
@sybix Thanks for the feedback. I would gladly accept a PR that adds a value to `production.yml` for this and changes to `index.php` that look for that value to be set.

**Comment by dbu** [comment]
according to https://symfony.com/blog/fixing-the-trusted-proxies-configuration-for-symfony-3-3 the trusted proxies should really be done in the frontend controller and not later. symfony 4 will mandate that way and not have a configuration for it anymore. maybe this should just be documented like that, or point to the relevant doc of silex.

**Comment by sybix** [comment]
Hi,

I have made a patch, i take the config from security.trusted_proxies in config file, and i use it in classes/Application.php

If it's ok, i can do the PR. I hope by the end of week.

**Comment by chartjes** [comment]
Closing since OpenCFP is migrating to Symfony 4
