### ISSUE TITLE
The API is broken

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#578]
# Steps required to reproduce the problem

1. run the app
2. go to /api/me

# Expected Result
See some kind of result

# Actual Result
Fatal error

The API requires League\OAuth2\ which isn't even in the composer.json anymore.

I'd like to know if there is any intention of getting it up and running at some point. And if its not, should tests etc for the API still be maintained. Or should it just be deleted all together?

Slightly related to #577

**Comment by mdwheele** [comment]
Looks like the dependency was accidentally dropped with the [Great Silex 2.0 Mergening](https://github.com/opencfp/opencfp/commit/36bf5a8ef4f172359b32b7f88275dad63283b284#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780)

**Comment by chartjes** [comment]
There is a plan afoot to build a SaaS for OpenCFP so I am planning on removing this feature for v2

**Comment by localheinz** [comment]
Noticed this as well when looking through the code, but wasn't entirely sure what the plans were with the code referencing the undefined classes.

Nice catch, @BackEndTea!

**Comment by enygma** [comment]
In poking around and trying to call the `/oauth/authorize` endpoint I get an error: 

```
Fatal error: Uncaught Error: Class 'OpenCFP\Provider\Gateways\AuthorizationServer' not found in /Users/ccornutt/tmp/opencfp/classes/Provider/Gateways/OAuthGatewayProvider.php
```

I'm guessing this has to do with the same thing?

**Comment by chartjes** [comment]
Removed from master branch
