### ISSUE TITLE
[RFC] Any interest in Dockerization of the OpenCFPs?

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#724]
I've been keeping a super-simple `docker-compose.yml` to the side for work I do on OpenCFP. Is there any interest in that? OpenCFP is one of the easier projects to set up so I don't know how much value there is in this, but figured I'd ask those involved.

Suggestion would be to store all of it in a directory named `.docker` at the root of the project. One "benefit" of using Docker is that there would be literally no difference in running builds locally vs on TravisCI at that point. We could make Travis use our Docker setup (https://docs.travis-ci.com/user/docker).

Stretch-goal: It could be a production deployment option for folks. Install Docker + Docker Compose, configure certs / application environment, run `docker-compose up -d` and run away!

Anywho, more or less just curious if there's interest. I know in the past we've tried our hands at having a "supported" `Vagrantfile` and eventually we ripped it out because it got a little too heavy.

**Comment by chartjes** [comment]
@mdwheele This dovetails nicely with my hope to have "hey, here's how to install this on Heroku" plans

**Comment by mdwheele** [comment]
Made it here, for now: https://github.com/mdwheele/opencfp-docker

It assumes latest stable version of Docker is installed and I've only done testing on Ubuntu and RHEL. There are some QoL things I'll add to it soon (need SSH keys sent to `workspace`, `git-completion`, etc.)

**Comment by mdwheele** [comment]
Closing this to continue in #928
