### ISSUE TITLE
[RFC] Remove dead code

### ISSUE THREAD

**Issue by BackEndTea** [opencfp/opencfp#743]
After the last few PR's we have a lot of dead code in the application.

* All Sentry specific classes (Providers/ Auth classes)
* API Code
  * ```Http/Api```
  * ```Http/Oauth```
  * ```Infrastructure/Oauth```
 * Api Gateways/ Providers
 * Tests for all those.

As far as Sentry goes, it can also be removed from composer. Unless we want to keep it in for a while, to allow people who wrote their own changes to OpenCFP to change to the sentinel implementation.

**Comment by mdwheele** [comment]
:+1: to remove all of those as well as the dependency on Sentry via Composer. Would you be down to send a PR? (*he asks knowing @BackEndTea is 100% down to PR*)

The way I see it: If folks have forks of the project with their own patches, patching `cartalyst/sentry` back into the project isn't too bad and keeps `upstream` clean. Alternatively, if we want to keep it, lets make sure to create an issue with a "drop by" date.

**Comment by BackEndTea** [comment]
I removed all of the dead code i could find, but kept the Sentry for now.
