### ISSUE TITLE
http://opencfp.com responds with 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#788]
# Steps required to reproduce the problem

1. Run

```
$ curl -I http://opencfp.com
```

# Expected Result

```
HTTP/1.1 200 OK
```

# Actual Result

```
HTTP/1.1 503 Service Temporarily Unavailable
``` 

Maybe we should do something with the domain?

**Comment by chartjes** [comment]
@localheinz I own opencfp.org so we should switch to that

**Comment by pmeth** [comment]
I have the domain opencfp.com. You guys can have it.

**Comment by localheinz** [comment]
Ha, nice, @pmeth!

**Comment by chartjes** [comment]
Will talk to @pmeth about transferring ownership
