### ISSUE TITLE
Ideal PHP-CS-Fixer Checks

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#810]
Cc: @localheinz @BackEndTea 

Currently, we're adding checks one by one to a "legacy" project and verifying tests we have still pass. Makes sense.

If we were starting fresh, what would our "ideal" code style checks look like? Would we grab `@PSR2`, `@Symfony`, `@PHP71Migration:risky` as a baseline and call it a day? Would we want additional checks on top of those? Would we be interested in maintaining a `@OpenCFP` rule-set? (I'd be down to contribute this to php-cs-fixer) I ask because we're planning on moving to Symfony and might have a lot of rules overlapping that now. Might be an opportunity to clean up? /shrug

Without a custom rule-set, I personally like the way @localheinz's [setup](https://github.com/localheinz/php-cs-fixer-config) works (speaking about keeping `.php_cs` light; pointed at configuration attached to source).

Any thoughts?

**Comment by BackEndTea** [comment]
In all honesty, it doesn't really matter *what* the rules are, as long as they are 'enforced'. To make sure the code looks the same everywhere. I'm down to use ```@PSR2```, ```@Symfony``` and whatever else is needed. 

I'd prefer to not add more dependencies then needed, so i'd rather just require php-cs-fixer, and set up the config ourselves.

**Comment by mdwheele** [comment]
> I'd prefer to not add more dependencies then needed, so i'd rather just require php-cs-fixer, and set up the config ourselves.

Definitely. Didn't mean to suggest adding any further dependencies simply for style enforcement. Mostly thinking forward to the impending splitting of this application into several bundles in possibly-different repositories. Would prefer to maintain similar style enforcement across both.

**Comment by localheinz** [comment]
I would suggest to do the following:

- enable and disable more fixers as we see fit (and both the language and tools evolve)
- when we want to apply the same coding standard consistently to other projects within this organization, extract a configuration similar to [`localheinz/php-cs-fixer-config`](https://github.com/localheinz/php-cs-fixer-config)

Enabling one fixer after another has worked fine for me for legacy projects, especially when test coverage is low. I did so at Refinery29, see [`refinery29/php-cs-fixer-config`](https://github.com/refinery29/php-cs-fixer-config).

**Comment by mdwheele** [comment]
Thanks for the discussion here! I think we're good to continue with the current direction.
