### ISSUE TITLE
RFC: Change to a train release model

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#811]
I am proposing we move from "Chris cuts a release whenever he feels like it's time" to "Chris cuts a release every Monday". This is referred to the "train model" at Mozilla -- whatever is on the train gets released.

**Comment by mdwheele** [comment]
Big fan. Such train. Much delivery.

**Comment by chartjes** [comment]
Closing this as the person who cuts the release is going to do it ;)
