### ISSUE TITLE
Do we prefer `@dataProviders` stick to array-of-arg-arrays, yield or /shrug?

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#873]
Related: https://github.com/opencfp/opencfp/pull/853#discussion_r155086734
Related: https://github.com/opencfp/opencfp/pull/871#discussion_r155227907

We've had a few PRs come in that use some arrangement of `yield` to return a `Generator` or `iterable` object. It looks like in both cases, this was done for readability, personal-preference, etc. My reviews have suggested sticking with array-of-arg-array madness as a matter of consistency, mostly. However, I am a proponent of doing what's most readable at the time with some reasonable default suggestions.

Things that go through my mind with data providers / readability:

* Named data-sets are a wonderful thing to help distinguish meaning / purpose for that dataset. They also improve test output on failure. Current codebase doesn't use them nearly enough.
  * #853 uses named data-sets to distinguish different scenarios
  * #871 returns `iterable` and uses multiple `yield` statements to separate.

  Thoughts: I would prefer use of named data-sets for new code, no matter the return type. We could definitely send some TLC to existing data providers.
* The biggest argument against array-of-arg-array madness is... it's mad. To me, it is a smell to have a test method that receives > 3 arguments from a data-provider. There are exceptions, but most times, it is a signal that the test method might be doing too much and is an opportunity to rethink models. This obviously doesn't apply so much to initial PRs against legacy, but that's my personal thought process.
  * Under that heuristic, the readability of array-of-arg-array madness is improved and is arguably equivalent to any `yield`-based solution.
  * Considering cases where a single argument is being sent, it's actually more code / arguably less-readable.

I'm making this issue to just open the discussion, but I don't think we need to bikeshed too much or anything like that. For now, I'm going to review in terms of consistency and we can organize a more-widespread effort to improve tests with regard to data providers in separate PRs.

**Comment by chartjes** [comment]
I want to see:

* named data sets
* continue to use array-of-arg-array for data providers

It also never occurred to me that too many arguments from a data provider was a combination test-and-code smell but upon reflection that makes sense.

I will submit a PR adding this requirement to the CONTRIBUING.md document

**Comment by localheinz** [comment]
What about naming of data providers?

We could enforce that data providers follow a specific naming scheme, too.

**Comment by chartjes** [comment]
@localheinz I am not sure how much I care about the name of a data provider, but open to suggestions

**Comment by mdwheele** [comment]
For reference, this code...

```php
<?php
use PHPUnit\Framework\TestCase;

class DataTest extends TestCase
{
    /**
     * @dataProvider additionProvider
     */
    public function testAdd($a, $b, $expected)
    {
        $this->assertEquals($expected, $a + $b);
    }

    public function additionProvider()
    {
        return [
            'adding zeros'  => [0, 0, 0],
            'zero plus one' => [0, 1, 1],
            'one plus zero' => [1, 0, 1],
            'one plus one'  => [1, 1, 3]
        ];
    }
}
?>
```

Fails like this...

```bash
phpunit DataTest
PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

...F

Time: 0 seconds, Memory: 5.75Mb

There was 1 failure:

1) DataTest::testAdd with data set "one plus one" (1, 1, 3)
Failed asserting that 2 matches expected 3.

/home/sb/DataTest.php:9

FAILURES!
Tests: 4, Assertions: 4, Failures: 1.
```

I value simplicity / readability of tests and output that points to the problem on failure. I think keeping it similar to the above example is reasonable. 

If we have anything that turns:

```php
return [
    'adding zeros'  => [0, 0, 0]
];
```

into...

```php
return [
    'adding zeros'  => [
        0, 
        0, 
        0
     ]
];
```

That would be nice to avoid.

**Comment by localheinz** [comment]
@chartjes 

As I personally prefer to prefix my test methods with `test` (as opposed to using the `@test` annotation), I also prefer to prefix my data provider methods with `provider`).

Similar to consistently suffixing controller actions with `Action`, this makes it easier to see what the purpose of a method is.

**Comment by BackEndTea** [comment]
@localheinz 
Thankfully there should be a php-cs fixer for the annotation or not soon.

**Comment by chartjes** [comment]
@localheinz I'm happy to add something to the contributing guidelines to prefix data provider methods with `provider`

I will insist on the @test annotation as I like how it results in more flexible test names

**Comment by chartjes** [comment]
Closing because It Has Been Decided we will go with array-of-arg-array for providers instead of using generators
