### ISSUE TITLE
Do we want to remove TestResponse in favour of providing assertions elsewhere?

### ISSUE THREAD

**Issue by localheinz** [opencfp/opencfp#877]
Currently, we use the [`TestResponse`](https://github.com/opencfp/opencfp/blob/ee3305b58f7054f2b242b748a29bc7fb68ad3806/tests/TestResponse.php) class as a means to simplify assertions on a response object returned from invoking a controller action.

As pointed out in https://github.com/opencfp/opencfp/pull/870/files#r155239203, I would suggest to remove the `TestResponse` class and instead provide domain-specific assertions either via 

- a trait
- an abstract test case

**Comment by chartjes** [comment]
👍 to making it a trait

**Comment by mdwheele** [comment]
From https://github.com/opencfp/opencfp/pull/870/files#r155252549:

> To be honest, I'm unsure how much WebTestCase really offers, if anything, other than a crutch to make it easier to test via an interface that feels more "end to end". If we were using Behat, would we even be having this discussion? Maybe not! I'd love to discuss / organize a plan in another issue.

Would we still need to address this problem if we implemented #774? With a reasonable Behat suite, I see little need for the types of tests that use `WebTestCase` (and by-extension, `TestResponse`)
