### ISSUE TITLE
Are there any PHP-CS-Fixer checks we could be using to enforce CONTRIBUTING.md

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#882]
See: https://github.com/opencfp/opencfp/pull/880

- **All test methods must have the `@test` annotation** -- We value descriptiveness in test method names
- **All data providers must return array-of-args-arrays** -- The use of generators may let us not remember the number of arguments but too many arguments is a sign of potential code- and test-smells
- **All data provider methods must be prefixed `provider`**
- **All test method names should be `snake_case_test_methods`** 

I know @BackEndTea is working on something for the `@test` annotation in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3275. There were hints of something to enforce `snake_case` vs `camelCase` as a separate PR.

Do we have anything for data providers? Anybody want to volunteer to start a PR :grin:

**Comment by BackEndTea** [comment]
Maybe i'm misunderstanding something, but wouldn't it make more sense to have dataproviders be suffixed with ```provider``` instead of prefixed?

```validRatingProvider()``` makes more sense then ```proivderForValidRatings()```

And issue number one will be resolved once my PR gets accepted. (Which i found a bug in when running it on this project code 😁)

I was planning on writing another fix after this one is all done, but i could take a look at camel to snake case, though there are about a million edge cases on that one, so i expect the fixer for that to take a while.

**Comment by BackEndTea** [comment]
I created an issue surrounding camel and snake case in https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3302 So we'll see if there is a desire for that one.

**Comment by keradus** [comment]
on the other side, we use convension for providers naming:
test method: `testFooBar`,
provider: `provideFooBarCases`
(as objects shall be named after nouns and methods after verbs)

**Comment by keradus** [comment]
I do believe that 1st, 3rd and 4th concepts could be done easily as fixers, 2nd could be challenging.
Yet, they have to be configured (like enforce one or other notation).

@BackEndTea is already done great work for 1st idea.
Would you consider picking up one of the rule and create a PR for it, @mdwheele  ?

**Comment by keradus** [comment]
(oh boy, I thought it's PHP CS Fixer repo, how did I get here? sorry ;) )

**Comment by mdwheele** [comment]
> And issue number one will be resolved once my PR gets accepted. (Which i found a bug in when running it on this project code )

Haha, I was reviewing open PR / issues last night looking for a fix I wanted and stumbled across your PR. So proud! :heart_eyes: 

> Maybe i'm misunderstanding something, but wouldn't it make more sense to have dataproviders be suffixed with provider instead of prefixed?

Oooooh, I misread that. I think you're right. We can open a PR for that. On the one hand, I like `provideScenariosForSomeBehaviour` for being able to quickly locate. I like assertive method names, in general. Maybe we just cut it to `provide`? At any rate, is there a "generic prefix methods blah blah blah" fixer we could be using?

**Comment by mdwheele** [comment]
> (oh boy, I thought it's PHP CS Fixer repo, how did I get here? sorry ;) )

Dude I just got SO CONFUSED because I posted a comment and thought I somehow ended up on the PHP-CS-Fixer repository... I think we're doing this open-source thing right.

**Comment by keradus** [comment]
I would strongly suggest to start with one of those fixers first, and typos one later.
typos fixer will be way more complicated, IMO it's better to start with simpler one.

**Comment by localheinz** [comment]
@BackEndTea @chartjes @mdwheele 

For me, the reasons for prefixing test methods and data providers are obvious:

* a test class only needs two kinds of `public` *instance* methods: test methods and data providers
* if a test class has any `public` *instance* methods that aren't **obviously** test methods or data providers, they can probably be removed, or should have `protected` or even `private` visibility
* by consistently using prefixes, there are no issues identifying what is a test or a data provider

On the other hand:

* using `@test` annotations adds more docblocks, and effectively more noise than using a `test` prefix
* using `Provider` as a suffix, as pointed out by @keradus, suggests we are talking about an object, not a method

But, since I'm only a contributor, not the owner of the repository, I don't mind following the rules - I just felt it necessary to explain my reasoning.

**Comment by mdwheele** [comment]
> But, since I'm only a contributor, not the owner of the repository, I don't mind following the rules - I just felt it necessary to explain my reasoning.

No worries at all. I feel like a lot of this is preferences and as we're seeing, OpenCFP doesn't really have a specific preference yet, so we're hashing it out now :smile: And with that said, I try and not hang onto my own personal preferences too tightly with this project. Just need to find something that works and is accessible to newcomers.

That said... personally,

```php
// In a unit test, I like methods that say *what* the SUT does...
public function it_quacks_like_a_duck() { }
public function it_walks_like_a_duck() { }
public function when_it_rains_it_turns_into_a_goat() { }

// When I see `test` prefixes, I feel like I'm repeating myself...
public function test_it_quacks_like_a_duck() { } // and so on...

// I know it's a test... I'm in `DuckTest`. Unfortunately, I have to let PHPUnit
// know this so... @test
```

When I run with the `--textdox` option, I like to see:

```bash
phpunit --testdox DuckTest
PHPUnit 6.5.0 by Sebastian Bergmann and contributors.

Duck
 [x] It quacks like a duck
 [x] It walks like a duck
```

versus...

```bash
Duck
 [x] Test it quacks like a duck
 [x] Test it walks like a duck
```

That said, I don't remember if `--testdox` strips the required prefix off. If it does, then I strike that portion of my "personal preference argument", lol.

**Comment by keradus** [comment]
so, basically, IMHO, you use PHPUnit to verify behaviour spec. Not to execute **unit** test.
it's not sth bad, just sth to be aware.
for pure unit test, you test given object, under which you test given concrete methods.
in pure utests, it's enough to have one test method (with data provider) per one src method.

**Comment by chartjes** [comment]
@keradus I find @mdwheele and I are are usually on the same page in wanting tests to be descriptive and like the "it_quacks_like_a_duck" format. Again, a lot of these are just personal preference but now that the number of contributors is expanding we need to write down some rules.

Hopefully a lot of these can be handled with `make cs` but actually looking at the code in the PR will catch them too.

Thanks so much for your feedback!

**Comment by keradus** [comment]
you could still achieve that with pure unit test with
```
@test
public function makeSound() { ... }

public function provideMakeSoundCases() {
    return [
        'barks like a dog' => ['dog', 'bark'],
        'quacks like a duck' => ['duck', 'quack'],
    ];
}
```

> Hopefully a lot of these can be handled with make cs but actually looking at the code in the PR will catch them too.

whatever approach is taken, automated detection would be great ;)
that's why, if one would start working on PR, we would simply need option to control it

**Comment by BackEndTea** [comment]
I agree that simply running ```make cs``` and having any standards like name suffixes/prefixes or having annotation would be fixed.
The second best option would be to have automated test that tell us something isn't right. 
Basically what is happening here already.  https://github.com/opencfp/opencfp/blob/52bf661fde9883c57ed042bc6ec49b2cac4548c0/tests/Unit/ProjectCodeTest.php#L143-L146

**Comment by keradus** [comment]
similar amount of work, so I would strongly suggest to make fixer rather than project code test ;)
especially as big part of it was already started by you ;)

btw, nice to see that my idea of ProjectCodeTest is spreading across different projects ;)
