### ISSUE TITLE
RFC:  Changing where images are uploaded

### ISSUE THREAD

**Issue by chartjes** [opencfp/opencfp#894]
In order to deploy to Heroku, we need to be able to change where our images are stored. https://devcenter.heroku.com/articles/s3#file-uploads talks about some potential solutions.

I tried abstracting out some stuff using Flysystem but I got stuck on not being able to create a backwards-compatible way of implementing it. Right now we assume all images uploaded will be served out of /uploads/<name of image> and we store the record in the database.

Open to suggestions on how to make the location configurable.

**Comment by BackEndTea** [comment]
👍  for Flysystem. One problem is that currently there is not a single place where the uploads location is defined.

There is the ```Path::uploadPath()``` function, but it is never actually used outside of its tests. Currently some views use the twig ```uploads``` function, some just add ```/uploads/``` to it themselves, and some expect it to be already prefixed with ```/uploads/``` by the controller.

So a first step would be to normalise the uploading and downloading of images, and have 2 ways of dealing with images.

1. A reference to the place it is uploaded to
2. A reference to the place it is downloaded from ( for display)

When saving to the local filesystem, these would be the same. But if we are saving to google cloud buckets for example, we use their stream wrapper to upload the images to a bucket, but we use the static url to display them.

**Comment by BackEndTea** [comment]
I made some first steps on solving this, but i think it might be smart to wait with implementing FlySystem until we fully made the change to Symfony, so we can use the [the FlySystem bundle](https://github.com/1up-lab/OneupFlysystemBundle).
