### ISSUE TITLE
Is there any reason to use Mockery and the PHPUnit mock facilities?

### ISSUE THREAD

**Issue by mdwheele** [opencfp/opencfp#983]
I've noticed recently we're using the PHPUnit mock facilities in new tests. We've previously preferred Mockery and had a few PHPUnit mocks sprinkled around like magic fairy dust :rainbow:.

Are there legitimate reasons for using both or is this another preference we should officially decide on? 

I personally like Mockery's interface better for readability. However, my opinion is not too strong on the matter. I mostly worry about newcomers wondering "Do I PHPUnit? Do I Mockery?" and bailing.

**Comment by localheinz** [comment]
We could also consider using `phpspec/prophecy`. 

Also see https://thephp.cc/news/2015/02/phpunit-4-5-and-prophecy.

**Comment by mdwheele** [comment]
> We could also consider using phpspec/prophecy.

I'm down with that. I've only ever looked at Prophecy through the eyes of PHPSpec, but if we picked this up, it looks like we'd be able to drop a dependency and keep something similar to the "more-readable" interface of Mockery.

**Comment by chartjes** [comment]
Prophecy is baked into PHPUnit these days so it's not the worst idea to use it. If the goal is to reduce dependencies, then this is a worthy task.

Personally I have moved to using Prophecy to teach folks in my workshops.

**Comment by mdwheele** [comment]
Let's do it!

For me, reducing dependencies happened to be a side-effect of making our approach to testing more consistent / accessible. For our current usage, it looks like Prophecy will be a great replacement for Mockery / current PHPUnit mocks.

Can we agree that new PRs that do any mock/stub should use Prophecy rather than PHPUnit mocks / Mockery?

**Comment by localheinz** [comment]
👍
